In [1]:
import pandas as pd

articles = pd.read_csv('./articles.csv')
customers = pd.read_csv('./customers.csv')
transactions = pd.read_csv('./transactions_train.csv')

print(articles.shape)
print(customers.shape)
print(transactions.shape)
print(articles.columns.tolist())

(105542, 25)
(1371980, 7)
(31788324, 5)
['article_id', 'product_code', 'prod_name', 'product_type_no', 'product_type_name', 'product_group_name', 'graphical_appearance_no', 'graphical_appearance_name', 'colour_group_code', 'colour_group_name', 'perceived_colour_value_id', 'perceived_colour_value_name', 'perceived_colour_master_id', 'perceived_colour_master_name', 'department_no', 'department_name', 'index_code', 'index_name', 'index_group_no', 'index_group_name', 'section_no', 'section_name', 'garment_group_no', 'garment_group_name', 'detail_desc']

In [2]:
print(articles.columns.tolist())
print(articles.head(2))

['article_id', 'product_code', 'prod_name', 'product_type_no', 'product_type_name', 'product_group_name', 'graphical_appearance_no', 'graphical_appearance_name', 'colour_group_code', 'colour_group_name', 'perceived_colour_value_id', 'perceived_colour_value_name', 'perceived_colour_master_id', 'perceived_colour_master_name', 'department_no', 'department_name', 'index_code', 'index_name', 'index_group_no', 'index_group_name', 'section_no', 'section_name', 'garment_group_no', 'garment_group_name', 'detail_desc']
   article_id  product_code  prod_name  product_type_no product_type_name  \
0   108775015        108775  Strap top              253          Vest top
1   108775044        108775  Strap top              253          Vest top

   product_group_name  graphical_appearance_no graphical_appearance_name  \
0  Garment Upper body                  1010016                     Solid
1  Garment Upper body                  1010016                     Solid

   colour_group_code colour_group_name  ...  department_name index_code  \
0                  9             Black  ...     Jersey Basic          A
1                 10             White  ...     Jersey Basic          A

   index_name index_group_no  index_group_name section_no  \
0  Ladieswear              1        Ladieswear         16
1  Ladieswear              1        Ladieswear         16

             section_name garment_group_no  garment_group_name  \
0  Womens Everyday Basics             1002        Jersey Basic
1  Womens Everyday Basics             1002        Jersey Basic

                               detail_desc
0  Jersey top with narrow shoulder straps.
1  Jersey top with narrow shoulder straps.

[2 rows x 25 columns]

In [3]:
print(articles['detail_desc'].head(10))
print(articles['detail_desc'].isna().sum())

0              Jersey top with narrow shoulder straps.
1              Jersey top with narrow shoulder straps.
2              Jersey top with narrow shoulder straps.
3    Microfibre T-shirt bra with underwired, moulde...
4    Microfibre T-shirt bra with underwired, moulde...
5    Microfibre T-shirt bra with underwired, moulde...
6    Semi shiny nylon stockings with a wide, reinfo...
7    Semi shiny nylon stockings with a wide, reinfo...
8    Tights with built-in support to lift the botto...
9    Semi shiny tights that shape the tummy, thighs...
Name: detail_desc, dtype: object
416

In [4]:
articles['text'] = (
    articles['prod_name'] + ' ' +
    articles['product_type_name'] + ' ' +
    articles['colour_group_name'] + ' ' +
    articles['garment_group_name'] + ' ' +
    articles['detail_desc'].fillna('')
)

print(articles['text'].head(3))

0    Strap top Vest top Black Jersey Basic Jersey t...
1    Strap top Vest top White Jersey Basic Jersey t...
2    Strap top (1) Vest top Off White Jersey Basic ...
Name: text, dtype: object

In [5]:
print(articles['text'].head()[0])

Strap top Vest top Black Jersey Basic Jersey top with narrow shoulder straps.

In [6]:
from sentence_transformers import SentenceTransformer

st_model = SentenceTransformer('all-MiniLM-L6-v2',device='cuda')

sample = articles['text'].head(1000).tolist()
embeddings = st_model.encode(sample, show_progress_bar=True)

print(embeddings.shape)

c:\Users\swson23\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

WARNING:tensorflow:From c:\Users\swson23\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

(1000, 384)

In [7]:
import numpy as np

all_texts = articles['text'].tolist()
all_embeddings = st_model.encode(all_texts, show_progress_bar=True, batch_size=256)

np.save('article_embeddings.npy', all_embeddings)
print(all_embeddings.shape)

Batches:   0%|          | 0/413 [00:00<?, ?it/s]

(105542, 384)

In [8]:
import faiss

dimension = all_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(all_embeddings.astype('float32'))

print(f"인덱스에 저장된 아이템 수: {index.ntotal}")

인덱스에 저장된 아이템 수: 105542

In [9]:
query = "casual summer white t-shirt"
query_embedding = st_model.encode([query])

D, I = index.search(query_embedding.astype('float32'), k=5)

print("검색 결과:")
for i, idx in enumerate(I[0]):
    print(f"{i+1}. {articles.iloc[idx]['prod_name']} - {articles.iloc[idx]['detail_desc']}")

검색 결과:
1. Summer price tee - T-shirt in soft cotton jersey with a print motif.
2. Summer price tee - T-shirt in soft cotton jersey with a print motif.
3. SG Summer Top - Wide-fitting sports top in fast-drying functional fabric with a print motif on the front, cap sleeves and a longer, sewn-in vest top with a racer back.
4. SUMMER Top - Short, wide, sports top in printed, fast-drying mesh layered over a vest top with a racer back.
5. SUMMER Top - Short, wide, sports top in printed, fast-drying mesh layered over a vest top with a racer back.

In [10]:
query = "casual summer white t-shirt"
query_embedding = st_model.encode([query])

D, I = index.search(query_embedding.astype('float32'), k=10)

# 중복 제거
seen = set()
results = []
for idx in I[0]:
    prod_name = articles.iloc[idx]['prod_name']
    if prod_name not in seen:
        seen.add(prod_name)
        results.append(idx)
    if len(results) == 5:
        break

print("검색 결과 (중복 제거):")
for i, idx in enumerate(results):
    print(f"{i+1}. {articles.iloc[idx]['prod_name']} - {articles.iloc[idx]['detail_desc']}")

검색 결과 (중복 제거):
1. Summer price tee - T-shirt in soft cotton jersey with a print motif.
2. SG Summer Top - Wide-fitting sports top in fast-drying functional fabric with a print motif on the front, cap sleeves and a longer, sewn-in vest top with a racer back.
3. SUMMER Top - Short, wide, sports top in printed, fast-drying mesh layered over a vest top with a racer back.
4. Summer top - Short, wide, sports top in printed, fast-drying mesh layered over a vest top with a racer back.
5. Summer graphic tee - T-shirt in soft jersey with a motif on the front.

In [11]:
print(transactions.head(3))
print(transactions.dtypes)

        t_dat                                        customer_id  article_id  \
0  2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   663713001
1  2018-09-20  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   541518023
2  2018-09-20  00007d2de826758b65a93dd24ce629ed66842531df6699...   505221004

      price  sales_channel_id
0  0.050831                 2
1  0.030492                 2
2  0.015237                 2
t_dat                object
customer_id          object
article_id            int64
price               float64
sales_channel_id      int64
dtype: object

In [12]:
# 구매 많은 유저 한 명 뽑기
top_user = transactions['customer_id'].value_counts().index[0]
user_history = transactions[transactions['customer_id'] == top_user]['article_id'].tolist()

print(f"유저 구매 아이템 수: {len(user_history)}")
print(f"구매한 아이템 예시:")
for aid in user_history[:3]:
    item = articles[articles['article_id'] == aid]
    if len(item) > 0:
        print(f"- {item.iloc[0]['prod_name']}")

유저 구매 아이템 수: 1895
구매한 아이템 예시:
- Skirt Pencil Stretch.
- Jafar
- Skirt Pencil Midi

In [13]:
##############################


# 유저 히스토리 임베딩 평균
article_id_to_idx = {aid: idx for idx, aid in enumerate(articles['article_id'])}

user_embeddings = []
for aid in user_history:
    if aid in article_id_to_idx:
        idx = article_id_to_idx[aid]
        user_embeddings.append(all_embeddings[idx])

user_vector = np.mean(user_embeddings, axis=0, keepdims=True)

# 추천
D, I = index.search(user_vector.astype('float32'), k=10)

seen = set(user_history)
results = []
for idx in I[0]:
    aid = articles.iloc[idx]['article_id']
    if aid not in seen:
        results.append(idx)
    if len(results) == 5:
        break

print("유저 맞춤 추천:")
for i, idx in enumerate(results):
    print(f"{i+1}. {articles.iloc[idx]['prod_name']} - {articles.iloc[idx]['detail_desc']}")
    
    ##############################

유저 맞춤 추천:
1. LASSIE LINEN L/S - Long-sleeved top in soft linen jersey with a V-neck and rounded hem. Longer at the back.
2. Twiggy - Calf-length dress in mesh with a low-cut back and long sleeves. Seam at the waist, a gently flared skirt and raw edges at the cuffs and hem. Jersey lining.
3. LASSIE LINEN L/S - Long-sleeved top in a linen weave with a V-neck. Slightly longer at the back.
4. LASSIE LINEN L/S - Long-sleeved top in soft linen jersey with a V-neck and rounded hem. Longer at the back.
5. LASSIE LINEN L/S - Long-sleeved top in soft linen jersey with a V-neck and rounded hem. Longer at the back.

In [14]:
seen_names = set()
seen_ids = set(user_history)
results = []

for idx in I[0]:
    aid = articles.iloc[idx]['article_id']
    name = articles.iloc[idx]['prod_name']
    if aid not in seen_ids and name not in seen_names:
        seen_names.add(name)
        results.append(idx)
    if len(results) == 5:
        break

print("유저 맞춤 추천 (중복 제거):")
for i, idx in enumerate(results):
    print(f"{i+1}. {articles.iloc[idx]['prod_name']} - {articles.iloc[idx]['detail_desc']}")

유저 맞춤 추천 (중복 제거):
1. LASSIE LINEN L/S - Long-sleeved top in soft linen jersey with a V-neck and rounded hem. Longer at the back.
2. Twiggy - Calf-length dress in mesh with a low-cut back and long sleeves. Seam at the waist, a gently flared skirt and raw edges at the cuffs and hem. Jersey lining.
3. RAVEN halfzip ls - Fitted running top in fast-drying functional fabric with a stand-up collar and zip at the top. Long sleeves with thumbholes at the cuffs, a small zipped pocket at the back, reflective details and a gently rounded hem. Slightly longer at the back. Soft brushed inside.
4. HEATHER halfzip ls - Fitted running top in fast-drying functional fabric with an elasticated hood and a zip at the top. Long raglan sleeves, a small zipped pocket at the back, reflective details and a gently rounded hem. Slightly longer at the back. Soft brushed inside.
5. ELENA baselayer - Base layer tights in a soft wool blend with an elasticated waist.

In [15]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "./qwen"
tokenizer = AutoTokenizer.from_pretrained(model_name)
qwen_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("모델 로드 완료!")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

모델 로드 완료!

In [16]:
def rerank_with_llm(query, candidates, top_k=3):
    candidate_text = "\n".join([
        f"{i+1}. {articles.iloc[idx]['prod_name']}: {articles.iloc[idx]['detail_desc']}"
        for i, idx in enumerate(candidates)
    ])
    
    prompt = f"""당신은 패션 추천 전문가입니다. 반드시 한국어로만 답변하세요. 한자나 중국어는 절대 사용하지 마세요.

사용자 검색어: "{query}"

후보 상품:
{candidate_text}

위 후보 중 가장 적합한 {top_k}개를 선택하고 이유를 설명하세요.
형식:
1. [상품 번호] - [이유]
2. [상품 번호] - [이유]
3. [상품 번호] - [이유]"""

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(qwen_model.device)
    outputs = qwen_model.generate(**inputs, max_new_tokens=200)
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    return response

query = "나한테 잘 맞는 옷"
query_embedding = st_model.encode([query])
D, I = index.search(query_embedding.astype('float32'), k=10)
result = rerank_with_llm(query, I[0][:5])
print(result)

1. 2 - [Mia l/s top] - 이 상품은 긴팔 티셔츠로, 여성의 청순하면서도 캐주얼한 분위기를 연출할 수 있습니다. 특히 둥근 네크라인이 있어 단정하면서도 자연스러운 이미지를 선사합니다.
2. 1 - [W GARDA SKIRT EQ] - 이 상품은 높은 워스트와detachable 티베이트 브레이크가 특징으로, 여성의 다이나믹한 스타일링을 돕습니다. 또한 앞면에 플래치 포켓과 밖으로 뻗어나온 티베이트 브레이크가 있어 다양한 스타일링 가능성을 제공합니다.
3. 5 - [Kardashian skirt (1)] - 이 상품은 강

In [95]:
user_vector = np.mean(user_embeddings, axis=0, keepdims=True)

D, I = index.search(user_vector.astype('float32'), k=20)

seen_names = set()
seen_ids = set(user_history)
candidates = []
for idx in I[0]:
    aid = articles.iloc[idx]['article_id']
    name = articles.iloc[idx]['prod_name']
    if aid not in seen_ids and name not in seen_names:
        seen_names.add(name)
        candidates.append(idx)
    if len(candidates) == 5:
        break

result = rerank_with_llm("이 유저의 구매 히스토리 기반 추천", candidates)
print(result)

1. 1 - [LASSIE LINEN L/S] - 이 유저의 구매 히스토리에서 라인 넷과 반원형 바지가 많이 구매되었고, 이 상품은 유아복 스타일의 롱슬리브 티셔츠로, 편안함과 착용감을 제공하여 아이들의 활동성을 돕기 좋습니다.
2. 3 - [RAVEN halfzip ls] - [HEATHER halfzip ls] - 이 두 상품 모두 빠르게 말리는 기능성 소재와 반바지 형태, 긴 손목 스트랩 및 반짝임 디테일 등이 유저의 구매 패턴에 잘 맞아 떨어집니다. 특히 빠른 말리는 특성으로 운동이나 활동 시 활용도가 높을 것으로 예상됩니다.
3. 5 - [ELENA baselayer] - 이 유저의 구매 히스토리에서 터틀넥과 반원형 바지가 주요 구매 트렌드였으므로, 이 상품은 기능성과 유아복 스타일을 동시에 만족시켜주며, 일상생활에서 활용도가 높을 것으로 보입니다.

In [32]:
import torch
print(torch.cuda.is_available())

True

In [30]:
import google.generativeai as genai

genai.configure(api_key="AIzaSyBKjF-m5lX-e_cf9XyIVdmZ-BRDzQR446o")

model = genai.GenerativeModel('gemini-2.5-flash-lite')
response = model.generate_content("안녕",request_options={"timeout": 30})
print(response.text)

안녕하세요! 무엇을 도와드릴까요?

In [27]:
for m in genai.list_models():
    if 'generateContent' in m.supported_generation_methods:
        print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025

In [31]:
import time
import json

def generate_korean_reasons_batch(items_batch):
    items_text = "\n".join([
        f"{i+1}. 상품명: {item['prod_name']}, 카테고리: {item['product_type_name']}, 색상: {item['colour_group_name']}, 설명: {item['detail_desc']}"
        for i, item in enumerate(items_batch)
    ])
    
    prompt = f"""당신은 패션 추천 전문가입니다. 반드시 한국어로만 답변하세요.

다음 패션 아이템들 각각을 추천하는 이유를 한국어로 2-3문장씩 작성해주세요.

{items_text}

형식:
1. [추천 이유]
2. [추천 이유]
3. [추천 이유]
..."""

    response = model.generate_content(prompt)
    
    # input-output 쌍으로 저장 (배치 단위)
    return {
        "input": items_text,
        "output": response.text
    }

training_data = []
batch_size = 10
for i in range(0, 100, batch_size):
    batch = [articles.iloc[j] for j in range(i, min(i+batch_size, 100))]
    result = generate_korean_reasons_batch(batch)
    training_data.append(result)
    time.sleep(12)
    print(f"{i+batch_size}/100 완료")

# 저장
with open('training_data.json', 'w', encoding='utf-8') as f:
    json.dump(training_data, f, ensure_ascii=False, indent=2)

print("완료!")

10/100 완료
20/100 완료
30/100 완료
40/100 완료
50/100 완료
60/100 완료
70/100 완료
80/100 완료
90/100 완료
100/100 완료
완료!

In [33]:
import json

with open('training_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"데이터 수: {len(data)}")
print(data[0])

데이터 수: 10
{'input': '1. 상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.\n2. 상품명: Strap top, 카테고리: Vest top, 색상: White, 설명: Jersey top with narrow shoulder straps.\n3. 상품명: Strap top (1), 카테고리: Vest top, 색상: Off White, 설명: Jersey top with narrow shoulder straps.\n4. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Black, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n5. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: White, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n6. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Light Beige, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n7. 상품명: 20 den 1p Stockings, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n8. 상품명: 20 den 1p Stockings, 카테고리: Socks, 색상: Beige, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n9. 상품명: Shape Up 30 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: Tights with built-in support to lift the bottom. Black in 30 denier and light amber in 15 denier.\n10. 상품명: Support 40 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny tights that shape the tummy, thighs and calves while also encouraging blood circulation in the legs. Elasticated waist.', 'output': '## 패션 추천 전문가의 아이템별 추천 이유\n\n### 1. 상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.\n\n*   **기본 아이템으로 활용도 만점:** 블랙 스트랩 탑은 어떤 하의와도 쉽게 매치할 수 있어 데일리룩부터 격식 있는 자리까지 두루 활용 가능한 필수 아이템입니다.\n*   **슬림한 실루엣 연출:** 좁은 어깨끈이 목선을 더욱 가늘어 보이게 하고, 군더더기 없는 디자인이 슬림한 상체 라인을 강조해 줍니다.\n*   **레이어드룩의 핵심:** 재킷이나 가디건 안에 이너로 착용하면 세련된 레이어드룩을 완성할 수 있으며, 시원한 여름철 단독 착용으로도 좋습니다.\n\n### 2. 상품명: Strap top, 카테고리: Vest top, 색상: White, 설명: Jersey top with narrow shoulder straps.\n\n*   **청량하고 화사한 분위기 연출:** 화이트 스트랩 탑은 깨끗하고 산뜻한 이미지를 더해주어 여름철 시원하고 밝은 느낌을 강조하고 싶을 때 완벽합니다.\n*   **어떤 스타일에도 자연스러운 조화:** 밝은 컬러는 어떤 색상의 옷과도 쉽게 매치되어 다양한 스타일링에 유연하게 활용될 수 있습니다.\n*   **레이어드의 기본 베이스:** 블랙 탑과 마찬가지로 다양한 아우터나 셔츠 안에 이너로 활용하여 깔끔하고 정돈된 느낌을 연출할 수 있습니다.\n\n### 3. 상품명: Strap top (1), 카테고리: Vest top, 색상: Off White, 설명: Jersey top with narrow shoulder straps.\n\n*   **부드럽고 고급스러운 무드:** 오프화이트 컬러는 화이트보다 차분하면서도 은은한 고급스러움을 더해주는 색감으로, 부드러운 인상을 주고 싶을 때 추천합니다.\n*   **페미닌한 매력 극대화:** 좁은 어깨끈 디자인과 함께 오프화이트 컬러가 여성스러운 매력을 더욱 돋보이게 하여 로맨틱한 스타일링에 제격입니다.\n*   **다양한 룩에 세련된 포인트:** 뉴트럴 톤 계열로 어떤 색상의 하의나 아우터와도 잘 어울리며, 톤온톤 코디를 통해 센스 있는 스타일을 완성할 수 있습니다.\n\n### 4. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Black, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n\n*   **매끄러운 T셔츠 라인 연출:** 노출이 없는 디자인과 부드러운 마이크로파이버 소재가 T셔츠 착용 시 봉제선이 드러나지 않아 매끈하고 깔끔한 T셔츠 핏을 완성해 줍니다.\n*   **편안함과 완벽한 서포트:** 와이어와 몰드 컵이 자연스러운 볼륨감을 살리면서도 안정적인 지지력을 제공하여 하루 종일 편안하게 착용 가능합니다.\n*   **기본 중의 기본, 블랙 브라:** 어떤 의상이든 비침 걱정 없이 착용할 수 있는 블랙 컬러는 다양한 옷차림에 필수적인 기본 아이템입니다.\n\n### 5. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: White, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n\n*   **밝은 색상의 의류에 최적화:** 얇거나 밝은 색상의 상의를 입을 때 비침 걱정을 덜어주어 깔끔하고 단정한 스타일링을 가능하게 합니다.\n*   **깨끗하고 화사한 느낌:** 화이트 컬러는 그 자체로도 청량감을 주며, 속옷으로서 가장 기본적인 컬러이기 때문에 활용도가 높습니다.\n*   **편안함과 자연스러운 실루엣:** 앞서 설명한 기능성을 그대로 갖추고 있어, 밝은 의상 착용 시에도 안정적인 착용감과 아름다운 실루엣을 유지시켜 줍니다.\n\n### 6. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Light Beige, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n\n*   **스킨톤에 자연스럽게 어우러짐:** 라이트 베이지 컬러는 피부톤과 유사하여 어떤 밝기의 의류에도 자연스럽게 녹아들어 속옷이 비치는 것을 효과적으로 방지해 줍니다.\n*   **섬세한 누드 톤 연출:** 특히 얇은 소재의 블라우스나 셔츠, 여름철 니트웨어 등에 완벽하게 어울리며, 은은하고 고급스러운 누드 톤 실루엣을 연출합니다.\n*   **안정적인 착용감과 자연스러운 모양:** 편안한 착용감과 가슴 모양을 자연스럽게 잡아주는 기능은 그대로 유지되어, 다양한 의상에 부담 없이 선택할 수 있습니다.\n\n### 7. 상품명: 20 den 1p Stockings, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n\n*   **클래식한 매력의 블랙 스타킹:** 세미 글로시한 블랙 컬러는 다리를 더욱 날씬하고 매끈하게 보이게 하며, 어떤 복장에도 격식과 섹시함을 더해주는 클래식한 아이템입니다.\n*   **다양한 스타일링에 활용:** 포멀한 오피스룩부터 특별한 날의 드레스 코디까지, 블랙 스타킹은 활용도가 매우 높아 하나쯤 구비해두면 좋습니다.\n*   **서스펜더 벨트와 함께 연출:** 넓고 강화된 윗부분 트림은 서스펜더 벨트와 함께 착용했을 때 더욱 안정적이고 스타일리시한 룩을 완성해 줍니다.\n\n### 8. 상품명: 20 den 1p Stockings, 카테고리: Socks, 색상: Beige, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n\n*   **자연스럽고 건강한 다리 라인 연출:** 베이지 컬러는 본연의 다리 색을 보정해주면서도 자연스럽게 혈색을 더해 건강하고 매끈한 다리 라인을 연출해 줍니다.\n*   **데일리룩에 활용도 높은 베이직 아이템:** 은은한 광택감과 베이지 컬러는 일상적인 의상에 과하지 않으면서도 세련된 포인트를 더해주어 매일 착용하기 좋습니다.\n*   **다양한 룩에 여성스러움을 더하기:** 스커트, 원피스 등 여성스러운 아이템과 함께 착용하면 더욱 우아하고 완성도 높은 스타일을 연출할 수 있습니다.\n\n### 9. 상품명: Shape Up 30 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: Tights with built-in support to lift the bottom. Black in 30 denier and light amber in 15 denier.\n\n*   **탄력 있는 힙 라인 연출:** 자체적인 보정 기능이 엉덩이를 자연스럽게 올려주어 옷맵시를 살려주고, 볼륨감 있는 힙 라인을 연출하는 데 도움을 줍니다.\n*   **매끈한 전체적인 실루엣 완성:** 30 데니어의 적절한 두께감이 하체 라인을 슬림하게 잡아주어 매끈하고 균형 잡힌 실루엣을 완성해 줍니다.\n*   **추운 날씨에도 스타일리시하게:** 블랙 컬러의 30 데니어 타이츠는 보온성과 함께 스타일까지 챙길 수 있어 겨울철 패션에 필수적인 아이템입니다.\n\n### 10. 상품명: Support 40 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny tights that shape the tummy, thighs and calves while also encouraging blood circulation in the legs. Elasticated waist.\n\n*   **탄탄한 보정력으로 슬림한 하체 완성:** 복부, 허벅지, 종아리까지 부드럽게 감싸주어 군살을 정리하고 매끈하고 슬림한 하체 라인을 만들어 줍니다.\n*   **혈액 순환 촉진으로 건강한 다리 관리:** 단순히 라인을 잡아주는 것을 넘어 혈액 순환을 도와 다리의 피로를 풀어주고 건강하게 관리하는 데 효과적입니다.\n*   **일상복에 편안함과 스타일을 더하다:** 세미 글로시한 블랙 컬러와 편안한 허리 밴딩은 데일리룩에 은은한 광택감과 함께 활동성을 더해주어 스타일과 실용성을 모두 갖춘 아이템입니다.'}

In [71]:
import json
import re
from pathlib import Path
from typing import Any


# 1) 파일 로드
DATA_PATH = Path(r"c:\Users\swson23\Desktop\test\llm_recommend\training_data.json")

with DATA_PATH.open(encoding="utf-8") as f:
    rows: list[dict[str, str]] = json.load(f)


# 2) input 파서: "1. 상품명: ..., 카테고리: ..., 색상: ..., 설명: ..."
INPUT_ITEM_RE = re.compile(
    r"^\s*(?P<no>\d+)\.\s*"
    r"상품명:\s*(?P<name>.*?),\s*"
    r"카테고리:\s*(?P<cat>.*?),\s*"
    r"색상:\s*(?P<color>.*?),\s*"
    r"설명:\s*(?P<desc>.*)\s*$"
)


def parse_input_block(text: str) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for line in text.splitlines():
        m = INPUT_ITEM_RE.match(line.strip())
        if not m:
            continue
        d = m.groupdict()
        d["no"] = int(d["no"])
        items.append(d)
    return items


# 3) output 파서: 번호 섹션 시작을 폭넓게 잡고(### 1. / **1. / 1.) 내용 누적
#   - "1." 만으로 시작하는 줄이 많으면 오탐이 생길 수 있어서, 제목에 상품 관련 키워드가 있으면 섹션으로 인정
OUTPUT_HEADER_RE = re.compile(
    r"^\s*(?:#+\s*)?(?:\*\*)?\s*(?P<no>\d+)\.\s*(?:\*\*)?\s*(?P<title>.*)\s*$"
)

OUTPUT_HEADER_HINTS = ("상품명", "카테고리", "색상", "(", ")")


def parse_output_block(text: str) -> dict[int, str]:
    blocks: dict[int, list[str]] = {}
    current_no: int | None = None

    for raw in text.splitlines():
        line = raw.rstrip()

        m = OUTPUT_HEADER_RE.match(line)
        if m:
            no = int(m.group("no"))
            title = (m.group("title") or "").strip()

            # 섹션 헤더로 보일 때만 시작(오탐 방지)
            if title and any(h in title for h in OUTPUT_HEADER_HINTS):
                current_no = no
                blocks.setdefault(no, []).append(line)
                continue

        if current_no is not None:
            blocks.setdefault(current_no, []).append(line)

    return {no: "\n".join(lines).strip() for no, lines in blocks.items()}


# 4) 한 샘플(input/output)에서 번호별 매칭
def match_one_example(example: dict[str, str]) -> list[dict[str, Any]]:
    input_items = parse_input_block(example["input"])     # list[{no,name,cat,color,desc}]
    output_blocks = parse_output_block(example["output"]) # dict[no] -> str

    matched: list[dict[str, Any]] = []
    for item in input_items:
        no = item["no"]
        matched.append(
            {
                "no": no,
                "input": item,
                "output": output_blocks.get(no, ""),  # 없으면 빈 문자열
            }
        )
    return matched


# 5) 전체 샘플(10개) 처리
all_pairs = [match_one_example(ex) for ex in rows]  # list[list[...]]


# 6) 평탄화: (example_idx, no) 단위의 레코드 1줄로
flat: list[dict[str, Any]] = []
for example_idx, pairs in enumerate(all_pairs):
    for p in pairs:
        flat.append(
            {
                "example_idx": example_idx,
                "no": p["no"],
                **p["input"],        # name/cat/color/desc
                "output": p["output"]
            }
        )

print("examples:", len(rows))
print("flat records:", len(flat))
print("sample flat[0]:", flat[0])

examples: 10
flat records: 100
sample flat[0]: {'example_idx': 0, 'no': 1, 'name': 'Strap top', 'cat': 'Vest top', 'color': 'Black', 'desc': 'Jersey top with narrow shoulder straps.', 'output': '### 1. 상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.\n\n*   **기본 아이템으로 활용도 만점:** 블랙 스트랩 탑은 어떤 하의와도 쉽게 매치할 수 있어 데일리룩부터 격식 있는 자리까지 두루 활용 가능한 필수 아이템입니다.\n*   **슬림한 실루엣 연출:** 좁은 어깨끈이 목선을 더욱 가늘어 보이게 하고, 군더더기 없는 디자인이 슬림한 상체 라인을 강조해 줍니다.\n*   **레이어드룩의 핵심:** 재킷이나 가디건 안에 이너로 착용하면 세련된 레이어드룩을 완성할 수 있으며, 시원한 여름철 단독 착용으로도 좋습니다.'}

In [78]:
def clean_output(text: str) -> str:
    # ### 번호. 상품명... 줄 제거
    cleaned = re.sub(r'^###?\s*\d+\..*?\n', '', text, flags=re.MULTILINE)
    # ** 볼드 마크다운 제거
    cleaned = re.sub(r'\*\*.*?\*\*', '', cleaned)
    # * 불릿 제거
    cleaned = re.sub(r'^\s*\*+\s*', '', cleaned, flags=re.MULTILINE)
    return cleaned.strip()

for item in flat:
    item['output'] = clean_output(item['output'])

print(flat[1]['output'])

화이트 스트랩 탑은 깨끗하고 산뜻한 이미지를 더해주어 여름철 시원하고 밝은 느낌을 강조하고 싶을 때 완벽합니다.
밝은 컬러는 어떤 색상의 옷과도 쉽게 매치되어 다양한 스타일링에 유연하게 활용될 수 있습니다.
블랙 탑과 마찬가지로 다양한 아우터나 셔츠 안에 이너로 활용하여 깔끔하고 정돈된 느낌을 연출할 수 있습니다.

In [79]:
fine_tuning_data = []
for item in flat:
    fine_tuning_data.append({
        "instruction": f"다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: {item['name']}, 카테고리: {item['cat']}, 색상: {item['color']}, 설명: {item['desc']}",
        "output": item['output']
    })

with open('fine_tuning_data.json', 'w', encoding='utf-8') as f:
    json.dump(fine_tuning_data, f, ensure_ascii=False, indent=2)

print(f"저장 완료! 총 {len(fine_tuning_data)}개")
print(fine_tuning_data[0])

저장 완료! 총 100개
{'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.', 'output': '블랙 스트랩 탑은 어떤 하의와도 쉽게 매치할 수 있어 데일리룩부터 격식 있는 자리까지 두루 활용 가능한 필수 아이템입니다.\n좁은 어깨끈이 목선을 더욱 가늘어 보이게 하고, 군더더기 없는 디자인이 슬림한 상체 라인을 강조해 줍니다.\n재킷이나 가디건 안에 이너로 착용하면 세련된 레이어드룩을 완성할 수 있으며, 시원한 여름철 단독 착용으로도 좋습니다.'}

In [80]:
fine_tuning_data

[{'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.',
  'output': '블랙 스트랩 탑은 어떤 하의와도 쉽게 매치할 수 있어 데일리룩부터 격식 있는 자리까지 두루 활용 가능한 필수 아이템입니다.\n좁은 어깨끈이 목선을 더욱 가늘어 보이게 하고, 군더더기 없는 디자인이 슬림한 상체 라인을 강조해 줍니다.\n재킷이나 가디건 안에 이너로 착용하면 세련된 레이어드룩을 완성할 수 있으며, 시원한 여름철 단독 착용으로도 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: White, 설명: Jersey top with narrow shoulder straps.',
  'output': '화이트 스트랩 탑은 깨끗하고 산뜻한 이미지를 더해주어 여름철 시원하고 밝은 느낌을 강조하고 싶을 때 완벽합니다.\n밝은 컬러는 어떤 색상의 옷과도 쉽게 매치되어 다양한 스타일링에 유연하게 활용될 수 있습니다.\n블랙 탑과 마찬가지로 다양한 아우터나 셔츠 안에 이너로 활용하여 깔끔하고 정돈된 느낌을 연출할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top (1), 카테고리: Vest top, 색상: Off White, 설명: Jersey top with narrow shoulder straps.',
  'output': '오프화이트 컬러는 화이트보다 차분하면서도 은은한 고급스러움을 더해주는 색감으로, 부드러운 인상을 주고 싶을 때 추천합니다.\n좁은 어깨끈 디자인과 함께 오프화이트 컬러가 여성스러운 매력을 더욱 돋보이게 하여 로맨틱한 스타일링에 제격입니다.\n뉴트럴 톤 계열로 어떤 색상의 하의나 아우터와도 잘 어울리며, 톤온톤 코디를 통해 센스 있는 스타일을 완성할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Black, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.',
  'output': '노출이 없는 디자인과 부드러운 마이크로파이버 소재가 T셔츠 착용 시 봉제선이 드러나지 않아 매끈하고 깔끔한 T셔츠 핏을 완성해 줍니다.\n와이어와 몰드 컵이 자연스러운 볼륨감을 살리면서도 안정적인 지지력을 제공하여 하루 종일 편안하게 착용 가능합니다.\n어떤 의상이든 비침 걱정 없이 착용할 수 있는 블랙 컬러는 다양한 옷차림에 필수적인 기본 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: White, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.',
  'output': '얇거나 밝은 색상의 상의를 입을 때 비침 걱정을 덜어주어 깔끔하고 단정한 스타일링을 가능하게 합니다.\n화이트 컬러는 그 자체로도 청량감을 주며, 속옷으로서 가장 기본적인 컬러이기 때문에 활용도가 높습니다.\n앞서 설명한 기능성을 그대로 갖추고 있어, 밝은 의상 착용 시에도 안정적인 착용감과 아름다운 실루엣을 유지시켜 줍니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Light Beige, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.',
  'output': '라이트 베이지 컬러는 피부톤과 유사하여 어떤 밝기의 의류에도 자연스럽게 녹아들어 속옷이 비치는 것을 효과적으로 방지해 줍니다.\n특히 얇은 소재의 블라우스나 셔츠, 여름철 니트웨어 등에 완벽하게 어울리며, 은은하고 고급스러운 누드 톤 실루엣을 연출합니다.\n편안한 착용감과 가슴 모양을 자연스럽게 잡아주는 기능은 그대로 유지되어, 다양한 의상에 부담 없이 선택할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 20 den 1p Stockings, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.',
  'output': '세미 글로시한 블랙 컬러는 다리를 더욱 날씬하고 매끈하게 보이게 하며, 어떤 복장에도 격식과 섹시함을 더해주는 클래식한 아이템입니다.\n포멀한 오피스룩부터 특별한 날의 드레스 코디까지, 블랙 스타킹은 활용도가 매우 높아 하나쯤 구비해두면 좋습니다.\n넓고 강화된 윗부분 트림은 서스펜더 벨트와 함께 착용했을 때 더욱 안정적이고 스타일리시한 룩을 완성해 줍니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 20 den 1p Stockings, 카테고리: Socks, 색상: Beige, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.',
  'output': '베이지 컬러는 본연의 다리 색을 보정해주면서도 자연스럽게 혈색을 더해 건강하고 매끈한 다리 라인을 연출해 줍니다.\n은은한 광택감과 베이지 컬러는 일상적인 의상에 과하지 않으면서도 세련된 포인트를 더해주어 매일 착용하기 좋습니다.\n스커트, 원피스 등 여성스러운 아이템과 함께 착용하면 더욱 우아하고 완성도 높은 스타일을 연출할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Shape Up 30 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: Tights with built-in support to lift the bottom. Black in 30 denier and light amber in 15 denier.',
  'output': '자체적인 보정 기능이 엉덩이를 자연스럽게 올려주어 옷맵시를 살려주고, 볼륨감 있는 힙 라인을 연출하는 데 도움을 줍니다.\n30 데니어의 적절한 두께감이 하체 라인을 슬림하게 잡아주어 매끈하고 균형 잡힌 실루엣을 완성해 줍니다.\n블랙 컬러의 30 데니어 타이츠는 보온성과 함께 스타일까지 챙길 수 있어 겨울철 패션에 필수적인 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Support 40 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny tights that shape the tummy, thighs and calves while also encouraging blood circulation in the legs. Elasticated waist.',
  'output': '복부, 허벅지, 종아리까지 부드럽게 감싸주어 군살을 정리하고 매끈하고 슬림한 하체 라인을 만들어 줍니다.\n단순히 라인을 잡아주는 것을 넘어 혈액 순환을 도와 다리의 피로를 풀어주고 건강하게 관리하는 데 효과적입니다.\n세미 글로시한 블랙 컬러와 편안한 허리 밴딩은 데일리룩에 은은한 광택감과 함께 활동성을 더해주어 스타일과 실용성을 모두 갖춘 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 200 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Opaque matt tights. 200 denier.',
  'output': '1.  \n200 데니어의 두께감과 불투명한 매트한 질감으로 보온성은 물론, 매끈하고 깔끔한 하체 라인을 연출하는 데 탁월합니다.\n블랙 컬러는 어떤 의상에도 매치하기 쉬워 활용도가 높으며, 겨울철 스커트나 원피스 착용 시 필수적인 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Grey, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.',
  'output': '2.  \n부드러운 오가닉 코튼 소재와 안감 기모 처리로 포근하고 편안한 착용감을 제공하여 데일리로 즐기기 좋습니다.\n그레이 컬러는 어떤 색상의 하의와도 자연스럽게 어울리며, 캐주얼하면서도 세련된 룩을 연출할 수 있습니다.\n(12-18개월, 18-24개월 사이즈 제외) 어깨 부분의 스냅 버튼은 아이가 입고 벗기 편리하도록 디자인되어 실용성을 더했습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Light Blue, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.',
  'output': '3.  \n부드러운 오가닉 코튼 소재와 안감 기모 처리로 포근하고 편안한 착용감을 제공하여 아이에게도 따뜻함을 선사합니다.\n산뜻한 라이트 블루 컬러는 화사하고 귀여운 느낌을 주며, 다양한 하의와 매치하여 사랑스러운 코디를 완성할 수 있습니다.\n(12-18개월, 18-24개월 사이즈 제외) 어깨 부분의 스냅 버튼은 아이가 입고 벗기 편리하도록 디자인되어 실용성을 더했습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: White, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.',
  'output': '4.  \n부드러운 저지 소재와 측면 서포트, 실리콘 트리밍 디테일로 편안하면서도 안정감 있는 착용감을 제공합니다.\n흰색은 깔끔하고 깨끗한 느낌을 주며, 다양한 상의나 이너웨어로 활용하기에 좋습니다.\n밴드 형태의 브라로 레이어드 룩이나 여름철 민소매 탑 안에 착용하기에 부담 없습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: Light Grey, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.',
  'output': '5.  \n부드러운 저지 소재와 측면 서포트, 실리콘 트리밍 디테일로 편안하면서도 안정감 있는 착용감을 제공합니다.\n라이트 그레이 컬러는 차분하고 세련된 느낌을 주며, 다양한 색상의 의상과 조화롭게 매치하기 좋습니다.\n밴드 형태의 브라로 레이어드 룩이나 여름철 민소매 탑 안에 착용하기에 부담 없습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Frugan longsleeve, 카테고리: Top, 색상: Dark Blue, 설명: Fitted top in soft stretch jersey with a wide neckline and long sleeves.',
  'output': '6.  \n신축성 좋은 부드러운 스트레치 저지 소재로 활동성을 보장하며, 몸에 자연스럽게 떨어지는 핏이 여성스러운 실루엣을 연출합니다.\n넓은 네크라인과 긴 소매 디자인은 단품으로 착용하거나 다양한 아우터 안에 이너로 활용하기에 적합합니다.\n다크 블루 컬러는 고급스러우면서도 캐주얼하게 연출할 수 있어 데일리룩으로 활용하기 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '7.  \n부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n다크 그레이 컬러는 어떤 상의와도 잘 어울리며, 베이직하면서도 스타일리시한 코디를 완성할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '8.  \n부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n그레이 컬러는 부드러운 느낌을 주며, 다양한 컬러의 상의와 매치하여 편안하면서도 스타일리시한 룩을 연출할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '9.  \n부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n블랙 컬러는 시크하고 날씬해 보이는 효과를 주며, 어떤 상의와도 매치하여 세련된 스트릿 패션을 완성할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '10. \n부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n다크 그레이 컬러는 어떤 상의와도 잘 어울리며, 베이직하면서도 스타일리시한 코디를 완성할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Pink, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '1.  \n편안함과 스타일을 동시에 잡고 싶을 때 제격입니다. 부드러운 기모 안감이 있어 포근하며, 톡톡 튀는 핑크 컬러는 캐주얼룩에 활기를 불어넣어 줄 거예요. 집 앞 외출이나 가벼운 운동 시에도 스타일리시하게 연출할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '2.  \n활용도 높은 기본템으로 어떤 상의와도 쉽게 매치됩니다. 부드러운 기모 안감은 편안함을 더해주며, 블랙 컬러는 슬림해 보이는 효과까지 선사합니다. 데일리룩부터 트레이닝복으로까지 다양하게 활용 가능합니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Blue, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '3.  \n청량하면서도 차분한 매력을 가진 다크 블루 조거팬츠입니다. 편안한 착용감은 물론, 청바지 느낌의 컬러로 캐주얼하면서도 세련된 스타일을 연출할 수 있습니다. 다양한 캐주얼 상의와 함께 코디하여 멋스러운 룩을 완성해보세요.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '4.  \n편안한 착용감과 군살 보정 효과를 동시에 원할 때 최고의 선택입니다. 넓은 허리 밴딩이 복부를 안정감 있게 잡아주어 어떤 활동에도 편안함을 제공합니다. 부드러운 저지 소재와 오가닉 코튼 함유로 피부에도 자극 없이 착용 가능합니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '5.  \n(4번과 동일) 편안한 착용감과 군살 보정 효과를 동시에 원할 때 최고의 선택입니다. 넓은 허리 밴딩이 복부를 안정감 있게 잡아주어 어떤 활동에도 편안함을 제공합니다. 부드러운 저지 소재와 오가닉 코튼 함유로 피부에도 자극 없이 착용 가능합니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Red, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '6.  \n평범한 레깅스에 지루함을 느낀다면, 매력적인 다크 레드 컬러로 포인트를 주세요. 부드러운 소재와 편안한 허리 밴딩은 활동성을 높여주며, 독특한 색감이 코디에 특별함을 더합니다. 니트나 롱 재킷과 함께 매치하여 세련된 가을/겨울 룩을 연출해보세요.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Grey, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '7.  \n세련되고 모던한 느낌을 주는 다크 그레이 레깅스는 어떤 룩에도 잘 어울립니다. 부드러운 저지 소재와 넓은 허리 밴딩으로 편안하게 착용할 수 있으며, 오가닉 코튼 함유로 자연 친화적인 아이템입니다. 다양한 컬러의 상의와 매치하여 시크한 데일리룩을 완성해보세요.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Control Top 50 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: 50 denier tights with reinforcement at the top for a shaping effect on the tummy and thighs.',
  'output': '8.  \n매끈하고 슬림한 라인을 연출하고 싶을 때 완벽한 아이템입니다. 50 데니어의 적절한 두께감과 컨트롤 탑 디자인이 복부와 허벅지를 부드럽게 잡아주어 보정 효과를 제공합니다. 어떤 옷에도 받쳐 입기 좋은 블랙 컬러로 활용도가 매우 높습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 2p Claw, 카테고리: Hair clip, 색상: Black, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '9.  \n심플하면서도 실용적인 블랙 컬러 헤어 집게는 데일리 헤어 스타일링에 필수품입니다. 3.5cm의 적당한 사이즈로 머리를 깔끔하게 고정해주며, 어떤 헤어 컬러나 스타일에나 자연스럽게 어울립니다. 간편하게 머리를 묶거나 스타일링을 완성할 때 유용합니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 2p Claw, 카테고리: Hair clip, 색상: Greyish Beige, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '10. \n은은하고 고급스러운 분위기를 연출하는 헤어 집게입니다. 뉴트럴 톤의 그레이쉬 베이지 컬러는 부드러운 인상을 주며, 다양한 헤어 스타일과 의상에 자연스럽게 조화됩니다. 3.5cm 사이즈로 머리를 자연스럽게 고정하고 세련된 포인트를 더하기 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 2p Claw, 카테고리: Hair clip, 색상: Light Orange, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '1.  \n화사한 라이트 오렌지 컬러는 산뜻하고 발랄한 느낌을 더해줍니다.\n가볍고 간편하게 헤어스타일을 연출할 수 있어 데일리로 활용하기 좋습니다.\n플라스틱 소재로 제작되어 물이나 땀에 강해 야외 활동 시에도 부담 없이 착용할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 2p Claw, 카테고리: Hair clip, 색상: Silver, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '2.  \n실버 컬러는 시크하고 모던한 분위기를 연출하여 어떤 스타일에도 잘 어울립니다.\n은은하게 빛나는 메탈릭 컬러가 고급스러움을 더해주어 포인트를 주기 좋습니다.\n가벼운 플라스틱 소재라 머리카락을 무겁게 누르지 않아 편안하게 착용할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 2p Claw, 카테고리: Hair clip, 색상: Gold, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '3.  \n골드 컬러는 화려하면서도 세련된 느낌을 주어 특별한 날이나 격식 있는 자리에 어울립니다.\n헤어스타일에 고급스러운 포인트를 더해주어 룩의 완성도를 높여줍니다.\n플라스틱 소재로 제작되어 착용감이 가볍고, 오래도록 변색 걱정 없이 사용할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Black, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '4.  \n블랙 컬러는 다리가 슬림해 보이는 효과를 주어 어떤 상의와도 매치하기 쉽습니다.\n신축성 좋은 소재와 편안한 허리 밴딩으로 활동성을 보장하며 데일리로 활용하기 좋습니다.\n3/4 기장으로 발목이 드러나 경쾌하고 스타일리시한 느낌을 연출할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: White, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '5.  \n화이트 컬러는 깨끗하고 화사한 느낌을 주어 봄, 여름철에 시원한 스타일링을 완성해 줍니다.\n어두운 색상의 상의나 아우터와 함께 매치하면 대비 효과를 주어 룩에 포인트를 줄 수 있습니다.\n신축성 좋은 소재와 편안한 착용감으로 활동량이 많은 날에도 부담 없이 입을 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Grey, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '6.  \n그레이 컬러는 부드럽고 세련된 느낌을 주어 차분하면서도 스타일리시한 코디를 연출할 수 있습니다.\n어떤 색상의 상의와도 무난하게 어울리지만, 채도가 낮은 색상과 함께 매치하면 더욱 멋스럽습니다.\n편안한 착용감과 3/4 기장으로 다양한 신발과 함께 매치하여 캐주얼한 룩을 완성하기 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Black Umbrella, 카테고리: Umbrella, 색상: Black, 설명: Umbrella with a telescopic handle and matching cover. Length 23 cm folded.',
  'output': '7.  \n클래식한 블랙 컬러는 어떤 상황에서도 튀지 않고 실용적으로 사용할 수 있습니다.\n테레스코픽 손잡이로 휴대 및 보관이 용이하며, 23cm의 컴팩트한 사이즈로 가방에 쏙 들어갑니다.\n갑작스러운 비에도 대비할 수 있도록 항상 휴대하기 좋은 필수 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: White, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.',
  'output': '8.  \n부드러운 벨루어 소재는 편안함과 포근함을 동시에 선사하여 집에서 휴식을 취할 때 최적입니다.\n귀여운 아플리케 디테일과 발 부분 디자인은 사랑스러운 매력을 더해주어 집에서도 스타일을 챙길 수 있게 해줍니다.\n화이트 컬러는 깨끗하고 화사한 느낌을 주며, 단추 디테일로 착용 및 탈의가 편리합니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.',
  'output': '9.  \n사랑스러운 라이트 핑크 컬러와 부드러운 벨루어 소재의 조화는 포근하고 여성스러운 무드를 연출합니다.\n앞면과 발 부분의 아플리케 디테일이 귀여움을 더해주어 편안함 속에서도 스타일을 놓치고 싶지 않은 분께 추천합니다.\n편리한 단추 여밈 방식과 편안한 핏으로 집에서의 휴식을 더욱 즐겁게 만들어 줄 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Mama 100 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Matt tights with an elasticated waist and extra space for a growing tummy. 100 denier.',
  'output': '10. \n100 데니아의 두께감으로 보온성을 제공하며, 쫀쫀한 신축성이 임산부의 편안한 착용감을 돕습니다.\n특히 복부를 위한 추가 공간 설계는 임신 기간 동안의 신체 변화에 맞춰 편안함을 극대화합니다.\n블랙 컬러는 다리를 슬림하고 길어 보이게 하는 효과와 함께 어떤 하의와도 매치하기 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '1.  \n[추천 이유] 블랙 컬러는 어떤 하의와도 매치하기 쉬운 클래식한 선택입니다.\n[추천 이유] 기능성 소재로 제작되어 활동적인 날에도 쾌적함을 유지할 수 있으며, 재활용 폴리에스터를 사용하여 지속 가능한 패션에도 기여합니다.\n[추천 이유] 오버로크 봉제선은 편안한 착용감을 제공하여 운동이나 일상복으로 활용하기 좋습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '2.  \n[추천 이유] 다크 그레이는 시크하면서도 차분한 느낌을 주어 다양한 스타일을 연출하기에 용이합니다.\n[추천 이유] 통기성과 속건성이 뛰어난 기능성 소재는 땀 흡수를 효과적으로 관리해주어 쾌적한 착용감을 선사합니다.\n[추천 이유] 환경을 생각한 재활용 폴리에스터 사용과 편안한 오버로크 봉제선은 이 스웨터를 실용적이고 가치 있는 아이템으로 만듭니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Sweater, 색상: White, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '3.  \n[추천 이유] 화이트 컬러는 깨끗하고 밝은 이미지를 더해주어 어떤 옷에도 산뜻함을 부여합니다.\n[추천 이유] 기능성 소재는 운동 시나 야외 활동 시 최적의 편안함과 쾌적함을 제공하며, 재활용 소재를 사용한 점도 긍정적입니다.\n[추천 이유] 심플한 디자인과 편안한 착용감으로 캐주얼룩부터 스포츠룩까지 다양하게 활용할 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Top, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '4.  \n[추천 이유] 블랙 롱슬리브 탑은 기본 아이템으로 활용도가 매우 높아 어떤 스타일에도 쉽게 매치할 수 있습니다.\n[추천 이유] 통기성과 속건성이 뛰어난 기능성 소재로 제작되어 운동이나 활동량이 많은 날에도 쾌적함을 유지시켜 줍니다.\n[추천 이유] 편안한 착용감과 환경을 고려한 재활용 소재 사용은 이 제품을 더욱 매력적으로 만듭니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Blue, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '5.  \n[추천 이유] 딥 블루 컬러는 세련되면서도 고급스러운 느낌을 주어 데일리룩에 포인트를 더하기 좋습니다.\n[추천 이유] 기능성 소재는 땀을 빠르게 말려주어 쾌적한 착용감을 유지시켜 주며, 지속 가능한 패션을 위한 재활용 폴리에스터 사용도 주목할 만합니다.\n[추천 이유] 편안한 오버로크 봉제선과 깔끔한 디자인으로 활동성과 스타일을 모두 만족시키는 아이템입니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '6.  \n[추천 이유] 다크 그레이는 부드러우면서도 세련된 느낌을 주어 어떤 룩에도 자연스럽게 어울립니다.\n[추천 이유] 속건성 및 통기성 좋은 기능성 소재와 편안한 오버로크 봉제선은 운동이나 일상생활에서 최상의 편안함을 선사합니다.\n[추천 이유] 재활용 폴리에스터를 사용하여 환경 보호에도 기여하는 윤리적인 선택이 될 수 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',
  'output': '7.  \n[추천 이유] 화이트 컬러의 민소매 바디수트는 깔끔하고 베이직하여 다양한 하의와 레이어드하기 좋습니다.\n[추천 이유] 부드러운 유기농 코튼 소재는 편안한 착용감을 제공하며, 밑단의 스냅 버튼은 착용 및 탈의를 편리하게 합니다.\n[추천 이유] 3개 세트로 구성되어 있어 실용적이며, 기본 아이템으로 어떤 코디에도 활용도가 높습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',
  'output': '8.  \n[추천 이유] 화이트 컬러의 민소매 바디수트는 다양한 스타일링을 위한 훌륭한 베이스 아이템입니다.\n[추천 이유] 부드러운 유기농 면 소재는 피부에 자극 없이 편안함을 제공하며, 밑단 스냅 버튼은 실용성을 더합니다.\n[추천 이유] 3개 세트로 구성되어 있어 활용도가 높으며, 어떤 룩에도 깔끔하게 매치할 수 있는 장점이 있습니다.'},
 {'instruction': '다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: 3P TANKTOP BODY, 카테고리: Bodysuit, 색상: Light Grey, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',

In [82]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model
from datasets import Dataset
import json

# 데이터 로드
with open('fine_tuning_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# 데이터셋 포맷 변환
def format_data(item):
    return {"text": f"### 지시사항:\n{item['instruction']}\n\n### 답변:\n{item['output']}"}

dataset = Dataset.from_list([format_data(item) for item in data])
print(dataset)

Dataset({
    features: ['text'],
    num_rows: 100
})

In [83]:
# 토크나이저 & 모델 로드
tokenizer = AutoTokenizer.from_pretrained("./qwen")
tokenizer.pad_token = tokenizer.eos_token

# 토크나이징
def tokenize(item):
    result = tokenizer(
        item["text"],
        truncation=True,
        max_length=512,
        padding="max_length"
    )
    result["labels"] = result["input_ids"].copy()
    return result

tokenized_dataset = dataset.map(tokenize, remove_columns=["text"])
print(tokenized_dataset)

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 100
})

In [84]:
# LoRA 설정
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

qwen_model = AutoModelForCausalLM.from_pretrained(
    "./qwen",
    torch_dtype=torch.float16,
    device_map="auto"
)

qwen_model = get_peft_model(qwen_model, lora_config)
qwen_model.print_trainable_parameters()

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 1,843,200 || all params: 3,087,781,888 || trainable%: 0.0597

In [87]:
training_args = TrainingArguments(
    output_dir="./qwen_finetuned",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    save_steps=50,
    warmup_steps=10,
    report_to="none",
    save_safetensors=False  # 이거 추가
)

trainer = Trainer(
    model=qwen_model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.

TrainOutput(global_step=39, training_loss=1.2273565194545648, metrics={'train_runtime': 43.2226, 'train_samples_per_second': 6.941, 'train_steps_per_second': 0.902, 'total_flos': 2558930190336000.0, 'train_loss': 1.2273565194545648, 'epoch': 3.0})

In [88]:
qwen_model.save_pretrained("./qwen_finetuned")
tokenizer.save_pretrained("./qwen_finetuned")
print("저장 완료!")

저장 완료!

In [93]:
from peft import PeftModel

# 파인튜닝된 모델 로드
base_model = AutoModelForCausalLM.from_pretrained(
    "./qwen",
    torch_dtype=torch.float16,
    device_map="cuda"
)
finetuned_model = PeftModel.from_pretrained(
    base_model, 
    "./qwen_finetuned",
    torch_dtype=torch.float16
)
finetuned_model = finetuned_model.merge_and_unload()

# 테스트
prompt = "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps."

messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(finetuned_model.device)
outputs = finetuned_model.generate(**inputs, max_new_tokens=500)
response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

黑色一字肩上衣是时尚界不可或缺的经典单品，无论搭配哪种风格的服装都能展现出独特的魅力。这款设计简约大方的上衣采用柔软舒适的网眼面料制作，不仅透气性好，还能轻松塑造完美的身形线条。黑色作为经典的配色，几乎可以与任何颜色的衣物搭配，无论是搭配休闲裤、牛仔裙还是高腰裤，都能营造出优雅而随性的感觉。

此外，这款上衣的设计特别之处在于其窄肩带的设计，不仅能够拉长颈部线条，还具有一定的装饰效果，使整体造型更加精致。不论是日常通勤还是周末约会，一条黑色一字肩上衣都是你衣橱中不可或缺的百搭神器。

In [94]:
prompt = "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps."

messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(finetuned_model.device)
outputs = finetuned_model.generate(**inputs, max_new_tokens=500)
response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

黑色紧身背心是打造简约时尚造型的绝佳选择，无论是搭配牛仔裤、休闲裤还是半身裙，都能展现出干练利落的气质。其细肩带设计既增加了整体造型的性感度，又不会过于张扬，非常适合日常通勤或休闲场合穿着。此外，黑色百搭的颜色也使得这款背心可以轻松与其他颜色的衣物搭配，提升整体造型的层次感。因此，这款黑色紧身背心绝对值得你的关注与尝试！

In [92]:
prompt = "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps."

messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(finetuned_model.device)
outputs = finetuned_model.generate(**inputs, max_new_tokens=500)
response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

黑色修身背心上衣は、スタイリングのアクセントを効果的に加えることができます。シンプルなデザインながら、細い肩紐で女性らしさを引き立て、様々なコーディネートにマッチします。ブラックはどんなアイテムとも相性よく、トレンド感のあるコーディネートを作り出すのに最適です。また、柔らかなジャージー素材を使用しているため、着心地も快適です。これからの季節に取り入れやすい、機能的でスタイリッシュなトップスです。

In [50]:
fine_tuning_data = []

#for batch in training_data:
#    print(batch)
    
    
batch['input']
#batch['output']

#1.  **상품명

'1. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Turquoise, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n2. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Dark Blue, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n3. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n4. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Turquoise, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n5. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Yellow, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n6. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Dark Blue, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n7. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n8. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Dark Blue, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n9. 상품명: FLEECE PYJAMA, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: All-in-one pyjamas in soft, patterned fleece that fasten down the front and along one leg. Ribbing at the cuffs and hems.\n10. 상품명: Mr Harrington w/hood, 카테고리: Hoodie, 색상: Black, 설명: Short, padded jacket with a jersey-lined hood and stand-up collar with a drawstring. Zip down the front, flap side pockets with a press-stud, one inner pocket, and ribbing at the cuffs and hem. Quilted lining.'

In [51]:
fine_tuning_data = []

for batch in training_data:
    # input을 번호 기준으로 분리
    input_items = re.split(r'\n(?=\d+\.)', batch['input'])
    input_items = [item.strip() for item in input_items if item.strip()]
    
    # output을 번호 기준으로 분리
    output_items = re.split(r'\n(?=\d+[\.\)])', batch['output'])
    output_items = [item.strip() for item in output_items if item.strip() and item[0].isdigit()]
    
    for i in range(min(len(input_items), len(output_items))):
        fine_tuning_data.append({
            "input": input_items[i],
            "output": output_items[i]
        })

print(f"파인튜닝 데이터 수: {len(fine_tuning_data)}")
print(fine_tuning_data[0])

파인튜닝 데이터 수: 70
{'input': '1. 상품명: 200 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Opaque matt tights. 200 denier.', 'output': '1.  **200 den 1p Tights (Black)**\n    *   200 데니어의 두께감과 불투명한 매트한 질감으로 보온성은 물론, 매끈하고 깔끔한 하체 라인을 연출하는 데 탁월합니다.\n    *   블랙 컬러는 어떤 의상에도 매치하기 쉬워 활용도가 높으며, 겨울철 스커트나 원피스 착용 시 필수적인 아이템입니다.'}

In [52]:
fine_tuning_data

[{'input': '1. 상품명: 200 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Opaque matt tights. 200 denier.',
  'output': '1.  **200 den 1p Tights (Black)**\n    *   200 데니어의 두께감과 불투명한 매트한 질감으로 보온성은 물론, 매끈하고 깔끔한 하체 라인을 연출하는 데 탁월합니다.\n    *   블랙 컬러는 어떤 의상에도 매치하기 쉬워 활용도가 높으며, 겨울철 스커트나 원피스 착용 시 필수적인 아이템입니다.'},
 {'input': '2. 상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Grey, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.',
  'output': '2.  **SWEATSHIRT OC (Grey)**\n    *   부드러운 오가닉 코튼 소재와 안감 기모 처리로 포근하고 편안한 착용감을 제공하여 데일리로 즐기기 좋습니다.\n    *   그레이 컬러는 어떤 색상의 하의와도 자연스럽게 어울리며, 캐주얼하면서도 세련된 룩을 연출할 수 있습니다.\n    *   (12-18개월, 18-24개월 사이즈 제외) 어깨 부분의 스냅 버튼은 아이가 입고 벗기 편리하도록 디자인되어 실용성을 더했습니다.'},
 {'input': '3. 상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Light Blue, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.',
  'output': '3.  **SWEATSHIRT OC (Light Blue)**\n    *   부드러운 오가닉 코튼 소재와 안감 기모 처리로 포근하고 편안한 착용감을 제공하여 아이에게도 따뜻함을 선사합니다.\n    *   산뜻한 라이트 블루 컬러는 화사하고 귀여운 느낌을 주며, 다양한 하의와 매치하여 사랑스러운 코디를 완성할 수 있습니다.\n    *   (12-18개월, 18-24개월 사이즈 제외) 어깨 부분의 스냅 버튼은 아이가 입고 벗기 편리하도록 디자인되어 실용성을 더했습니다.'},
 {'input': '4. 상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: White, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.',
  'output': '4.  **Alice BANDEAU 2-p (White)**\n    *   부드러운 저지 소재와 측면 서포트, 실리콘 트리밍 디테일로 편안하면서도 안정감 있는 착용감을 제공합니다.\n    *   흰색은 깔끔하고 깨끗한 느낌을 주며, 다양한 상의나 이너웨어로 활용하기에 좋습니다.\n    *   밴드 형태의 브라로 레이어드 룩이나 여름철 민소매 탑 안에 착용하기에 부담 없습니다.'},
 {'input': '5. 상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: Light Grey, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.',
  'output': '5.  **Alice BANDEAU 2-p (Light Grey)**\n    *   부드러운 저지 소재와 측면 서포트, 실리콘 트리밍 디테일로 편안하면서도 안정감 있는 착용감을 제공합니다.\n    *   라이트 그레이 컬러는 차분하고 세련된 느낌을 주며, 다양한 색상의 의상과 조화롭게 매치하기 좋습니다.\n    *   밴드 형태의 브라로 레이어드 룩이나 여름철 민소매 탑 안에 착용하기에 부담 없습니다.'},
 {'input': '6. 상품명: Frugan longsleeve, 카테고리: Top, 색상: Dark Blue, 설명: Fitted top in soft stretch jersey with a wide neckline and long sleeves.',
  'output': '6.  **Frugan longsleeve (Dark Blue)**\n    *   신축성 좋은 부드러운 스트레치 저지 소재로 활동성을 보장하며, 몸에 자연스럽게 떨어지는 핏이 여성스러운 실루엣을 연출합니다.\n    *   넓은 네크라인과 긴 소매 디자인은 단품으로 착용하거나 다양한 아우터 안에 이너로 활용하기에 적합합니다.\n    *   다크 블루 컬러는 고급스러우면서도 캐주얼하게 연출할 수 있어 데일리룩으로 활용하기 좋습니다.'},
 {'input': '7. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '7.  **Jerry jogger bottoms (Dark Grey)**\n    *   부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n    *   조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n    *   다크 그레이 컬러는 어떤 상의와도 잘 어울리며, 베이직하면서도 스타일리시한 코디를 완성할 수 있습니다.'},
 {'input': '8. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '8.  **Jerry jogger bottoms (Grey)**\n    *   부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n    *   조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n    *   그레이 컬러는 부드러운 느낌을 주며, 다양한 컬러의 상의와 매치하여 편안하면서도 스타일리시한 룩을 연출할 수 있습니다.'},
 {'input': '9. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '9.  **Jerry jogger bottoms (Black)**\n    *   부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n    *   조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n    *   블랙 컬러는 시크하고 날씬해 보이는 효과를 주며, 어떤 상의와도 매치하여 세련된 스트릿 패션을 완성할 수 있습니다.'},
 {'input': '10. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '10. **Jerry jogger bottoms (Dark Grey)**\n    *   부드러운 기모 안감 처리된 스웻셔츠 소재로 포근하고 편안하며, 활동적인 움직임에도 편안함을 제공합니다.\n    *   조절 가능한 스트링 허리, 사이드 및 뒷면 포켓, 리브드 밑단은 실용성과 트렌디함을 동시에 갖추고 있어 캐주얼룩에 제격입니다.\n    *   다크 그레이 컬러는 어떤 상의와도 잘 어울리며, 베이직하면서도 스타일리시한 코디를 완성할 수 있습니다.'},
 {'input': '1. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Pink, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '1.  **상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Pink**\n    *   편안함과 스타일을 동시에 잡고 싶을 때 제격입니다. 부드러운 기모 안감이 있어 포근하며, 톡톡 튀는 핑크 컬러는 캐주얼룩에 활기를 불어넣어 줄 거예요. 집 앞 외출이나 가벼운 운동 시에도 스타일리시하게 연출할 수 있습니다.'},
 {'input': '2. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '2.  **상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black**\n    *   활용도 높은 기본템으로 어떤 상의와도 쉽게 매치됩니다. 부드러운 기모 안감은 편안함을 더해주며, 블랙 컬러는 슬림해 보이는 효과까지 선사합니다. 데일리룩부터 트레이닝복으로까지 다양하게 활용 가능합니다.'},
 {'input': '3. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Blue, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.',
  'output': '3.  **상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Blue**\n    *   청량하면서도 차분한 매력을 가진 다크 블루 조거팬츠입니다. 편안한 착용감은 물론, 청바지 느낌의 컬러로 캐주얼하면서도 세련된 스타일을 연출할 수 있습니다. 다양한 캐주얼 상의와 함께 코디하여 멋스러운 룩을 완성해보세요.'},
 {'input': '4. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '4.  **상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black**\n    *   편안한 착용감과 군살 보정 효과를 동시에 원할 때 최고의 선택입니다. 넓은 허리 밴딩이 복부를 안정감 있게 잡아주어 어떤 활동에도 편안함을 제공합니다. 부드러운 저지 소재와 오가닉 코튼 함유로 피부에도 자극 없이 착용 가능합니다.'},
 {'input': '5. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '5.  **상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black**\n    *   (4번과 동일) 편안한 착용감과 군살 보정 효과를 동시에 원할 때 최고의 선택입니다. 넓은 허리 밴딩이 복부를 안정감 있게 잡아주어 어떤 활동에도 편안함을 제공합니다. 부드러운 저지 소재와 오가닉 코튼 함유로 피부에도 자극 없이 착용 가능합니다.'},
 {'input': '6. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Red, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '6.  **상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Red**\n    *   평범한 레깅스에 지루함을 느낀다면, 매력적인 다크 레드 컬러로 포인트를 주세요. 부드러운 소재와 편안한 허리 밴딩은 활동성을 높여주며, 독특한 색감이 코디에 특별함을 더합니다. 니트나 롱 재킷과 함께 매치하여 세련된 가을/겨울 룩을 연출해보세요.'},
 {'input': '7. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Grey, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '7.  **상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Grey**\n    *   세련되고 모던한 느낌을 주는 다크 그레이 레깅스는 어떤 룩에도 잘 어울립니다. 부드러운 저지 소재와 넓은 허리 밴딩으로 편안하게 착용할 수 있으며, 오가닉 코튼 함유로 자연 친화적인 아이템입니다. 다양한 컬러의 상의와 매치하여 시크한 데일리룩을 완성해보세요.'},
 {'input': '8. 상품명: Control Top 50 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: 50 denier tights with reinforcement at the top for a shaping effect on the tummy and thighs.',
  'output': '8.  **상품명: Control Top 50 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black**\n    *   매끈하고 슬림한 라인을 연출하고 싶을 때 완벽한 아이템입니다. 50 데니어의 적절한 두께감과 컨트롤 탑 디자인이 복부와 허벅지를 부드럽게 잡아주어 보정 효과를 제공합니다. 어떤 옷에도 받쳐 입기 좋은 블랙 컬러로 활용도가 매우 높습니다.'},
 {'input': '9. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Black, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '9.  **상품명: 2p Claw, 카테고리: Hair clip, 색상: Black**\n    *   심플하면서도 실용적인 블랙 컬러 헤어 집게는 데일리 헤어 스타일링에 필수품입니다. 3.5cm의 적당한 사이즈로 머리를 깔끔하게 고정해주며, 어떤 헤어 컬러나 스타일에나 자연스럽게 어울립니다. 간편하게 머리를 묶거나 스타일링을 완성할 때 유용합니다.'},
 {'input': '10. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Greyish Beige, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '10. **상품명: 2p Claw, 카테고리: Hair clip, 색상: Greyish Beige**\n    *   은은하고 고급스러운 분위기를 연출하는 헤어 집게입니다. 뉴트럴 톤의 그레이쉬 베이지 컬러는 부드러운 인상을 주며, 다양한 헤어 스타일과 의상에 자연스럽게 조화됩니다. 3.5cm 사이즈로 머리를 자연스럽게 고정하고 세련된 포인트를 더하기 좋습니다.'},
 {'input': '1. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Light Orange, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '1.  **상품명: 2p Claw, 카테고리: Hair clip, 색상: Light Orange**\n    *   화사한 라이트 오렌지 컬러는 산뜻하고 발랄한 느낌을 더해줍니다.\n    *   가볍고 간편하게 헤어스타일을 연출할 수 있어 데일리로 활용하기 좋습니다.\n    *   플라스틱 소재로 제작되어 물이나 땀에 강해 야외 활동 시에도 부담 없이 착용할 수 있습니다.'},
 {'input': '2. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Silver, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '2.  **상품명: 2p Claw, 카테고리: Hair clip, 색상: Silver**\n    *   실버 컬러는 시크하고 모던한 분위기를 연출하여 어떤 스타일에도 잘 어울립니다.\n    *   은은하게 빛나는 메탈릭 컬러가 고급스러움을 더해주어 포인트를 주기 좋습니다.\n    *   가벼운 플라스틱 소재라 머리카락을 무겁게 누르지 않아 편안하게 착용할 수 있습니다.'},
 {'input': '3. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Gold, 설명: Plastic hair claws. Width 3.5 cm.',
  'output': '3.  **상품명: 2p Claw, 카테고리: Hair clip, 색상: Gold**\n    *   골드 컬러는 화려하면서도 세련된 느낌을 주어 특별한 날이나 격식 있는 자리에 어울립니다.\n    *   헤어스타일에 고급스러운 포인트를 더해주어 룩의 완성도를 높여줍니다.\n    *   플라스틱 소재로 제작되어 착용감이 가볍고, 오래도록 변색 걱정 없이 사용할 수 있습니다.'},
 {'input': '4. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Black, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '4.  **상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Black**\n    *   블랙 컬러는 다리가 슬림해 보이는 효과를 주어 어떤 상의와도 매치하기 쉽습니다.\n    *   신축성 좋은 소재와 편안한 허리 밴딩으로 활동성을 보장하며 데일리로 활용하기 좋습니다.\n    *   3/4 기장으로 발목이 드러나 경쾌하고 스타일리시한 느낌을 연출할 수 있습니다.'},
 {'input': '5. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: White, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '5.  **상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: White**\n    *   화이트 컬러는 깨끗하고 화사한 느낌을 주어 봄, 여름철에 시원한 스타일링을 완성해 줍니다.\n    *   어두운 색상의 상의나 아우터와 함께 매치하면 대비 효과를 주어 룩에 포인트를 줄 수 있습니다.\n    *   신축성 좋은 소재와 편안한 착용감으로 활동량이 많은 날에도 부담 없이 입을 수 있습니다.'},
 {'input': '6. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Grey, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.',
  'output': '6.  **상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Grey**\n    *   그레이 컬러는 부드럽고 세련된 느낌을 주어 차분하면서도 스타일리시한 코디를 연출할 수 있습니다.\n    *   어떤 색상의 상의와도 무난하게 어울리지만, 채도가 낮은 색상과 함께 매치하면 더욱 멋스럽습니다.\n    *   편안한 착용감과 3/4 기장으로 다양한 신발과 함께 매치하여 캐주얼한 룩을 완성하기 좋습니다.'},
 {'input': '7. 상품명: Black Umbrella, 카테고리: Umbrella, 색상: Black, 설명: Umbrella with a telescopic handle and matching cover. Length 23 cm folded.',
  'output': '7.  **상품명: Black Umbrella, 카테고리: Umbrella, 색상: Black**\n    *   클래식한 블랙 컬러는 어떤 상황에서도 튀지 않고 실용적으로 사용할 수 있습니다.\n    *   테레스코픽 손잡이로 휴대 및 보관이 용이하며, 23cm의 컴팩트한 사이즈로 가방에 쏙 들어갑니다.\n    *   갑작스러운 비에도 대비할 수 있도록 항상 휴대하기 좋은 필수 아이템입니다.'},
 {'input': '8. 상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: White, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.',
  'output': '8.  **상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: White**\n    *   부드러운 벨루어 소재는 편안함과 포근함을 동시에 선사하여 집에서 휴식을 취할 때 최적입니다.\n    *   귀여운 아플리케 디테일과 발 부분 디자인은 사랑스러운 매력을 더해주어 집에서도 스타일을 챙길 수 있게 해줍니다.\n    *   화이트 컬러는 깨끗하고 화사한 느낌을 주며, 단추 디테일로 착용 및 탈의가 편리합니다.'},
 {'input': '9. 상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.',
  'output': '9.  **상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink**\n    *   사랑스러운 라이트 핑크 컬러와 부드러운 벨루어 소재의 조화는 포근하고 여성스러운 무드를 연출합니다.\n    *   앞면과 발 부분의 아플리케 디테일이 귀여움을 더해주어 편안함 속에서도 스타일을 놓치고 싶지 않은 분께 추천합니다.\n    *   편리한 단추 여밈 방식과 편안한 핏으로 집에서의 휴식을 더욱 즐겁게 만들어 줄 아이템입니다.'},
 {'input': '10. 상품명: Mama 100 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Matt tights with an elasticated waist and extra space for a growing tummy. 100 denier.',
  'output': '10. **상품명: Mama 100 den 1p Tights, 카테고리: Underwear Tights, 색상: Black**\n    *   100 데니아의 두께감으로 보온성을 제공하며, 쫀쫀한 신축성이 임산부의 편안한 착용감을 돕습니다.\n    *   특히 복부를 위한 추가 공간 설계는 임신 기간 동안의 신체 변화에 맞춰 편안함을 극대화합니다.\n    *   블랙 컬러는 다리를 슬림하고 길어 보이게 하는 효과와 함께 어떤 하의와도 매치하기 좋습니다.'},
 {'input': '1. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '1.  **상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Black**\n    *   [추천 이유] 블랙 컬러는 어떤 하의와도 매치하기 쉬운 클래식한 선택입니다.\n    *   [추천 이유] 기능성 소재로 제작되어 활동적인 날에도 쾌적함을 유지할 수 있으며, 재활용 폴리에스터를 사용하여 지속 가능한 패션에도 기여합니다.\n    *   [추천 이유] 오버로크 봉제선은 편안한 착용감을 제공하여 운동이나 일상복으로 활용하기 좋습니다.'},
 {'input': '2. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '2.  **상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey**\n    *   [추천 이유] 다크 그레이는 시크하면서도 차분한 느낌을 주어 다양한 스타일을 연출하기에 용이합니다.\n    *   [추천 이유] 통기성과 속건성이 뛰어난 기능성 소재는 땀 흡수를 효과적으로 관리해주어 쾌적한 착용감을 선사합니다.\n    *   [추천 이유] 환경을 생각한 재활용 폴리에스터 사용과 편안한 오버로크 봉제선은 이 스웨터를 실용적이고 가치 있는 아이템으로 만듭니다.'},
 {'input': '3. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: White, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '3.  **상품명: Dorian l/s basic, 카테고리: Sweater, 색상: White**\n    *   [추천 이유] 화이트 컬러는 깨끗하고 밝은 이미지를 더해주어 어떤 옷에도 산뜻함을 부여합니다.\n    *   [추천 이유] 기능성 소재는 운동 시나 야외 활동 시 최적의 편안함과 쾌적함을 제공하며, 재활용 소재를 사용한 점도 긍정적입니다.\n    *   [추천 이유] 심플한 디자인과 편안한 착용감으로 캐주얼룩부터 스포츠룩까지 다양하게 활용할 수 있습니다.'},
 {'input': '4. 상품명: Dorian l/s basic, 카테고리: Top, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '4.  **상품명: Dorian l/s basic, 카테고리: Top, 색상: Black**\n    *   [추천 이유] 블랙 롱슬리브 탑은 기본 아이템으로 활용도가 매우 높아 어떤 스타일에도 쉽게 매치할 수 있습니다.\n    *   [추천 이유] 통기성과 속건성이 뛰어난 기능성 소재로 제작되어 운동이나 활동량이 많은 날에도 쾌적함을 유지시켜 줍니다.\n    *   [추천 이유] 편안한 착용감과 환경을 고려한 재활용 소재 사용은 이 제품을 더욱 매력적으로 만듭니다.'},
 {'input': '5. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Blue, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '5.  **상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Blue**\n    *   [추천 이유] 딥 블루 컬러는 세련되면서도 고급스러운 느낌을 주어 데일리룩에 포인트를 더하기 좋습니다.\n    *   [추천 이유] 기능성 소재는 땀을 빠르게 말려주어 쾌적한 착용감을 유지시켜 주며, 지속 가능한 패션을 위한 재활용 폴리에스터 사용도 주목할 만합니다.\n    *   [추천 이유] 편안한 오버로크 봉제선과 깔끔한 디자인으로 활동성과 스타일을 모두 만족시키는 아이템입니다.'},
 {'input': '6. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.',
  'output': '6.  **상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey**\n    *   [추천 이유] 다크 그레이는 부드러우면서도 세련된 느낌을 주어 어떤 룩에도 자연스럽게 어울립니다.\n    *   [추천 이유] 속건성 및 통기성 좋은 기능성 소재와 편안한 오버로크 봉제선은 운동이나 일상생활에서 최상의 편안함을 선사합니다.\n    *   [추천 이유] 재활용 폴리에스터를 사용하여 환경 보호에도 기여하는 윤리적인 선택이 될 수 있습니다.'},
 {'input': '7. 상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',
  'output': '7.  **상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White**\n    *   [추천 이유] 화이트 컬러의 민소매 바디수트는 깔끔하고 베이직하여 다양한 하의와 레이어드하기 좋습니다.\n    *   [추천 이유] 부드러운 유기농 코튼 소재는 편안한 착용감을 제공하며, 밑단의 스냅 버튼은 착용 및 탈의를 편리하게 합니다.\n    *   [추천 이유] 3개 세트로 구성되어 있어 실용적이며, 기본 아이템으로 어떤 코디에도 활용도가 높습니다.'},
 {'input': '8. 상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',
  'output': '8.  **상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White**\n    *   [추천 이유] 화이트 컬러의 민소매 바디수트는 다양한 스타일링을 위한 훌륭한 베이스 아이템입니다.\n    *   [추천 이유] 부드러운 유기농 면 소재는 피부에 자극 없이 편안함을 제공하며, 밑단 스냅 버튼은 실용성을 더합니다.\n    *   [추천 이유] 3개 세트로 구성되어 있어 활용도가 높으며, 어떤 룩에도 깔끔하게 매치할 수 있는 장점이 있습니다.'},
 {'input': '9. 상품명: 3P TANKTOP BODY, 카테고리: Bodysuit, 색상: Light Grey, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.',
  'output': '9.  **상품명: 3P TANKTOP BODY, 카테고리: Bodysuit, 색상: Light Grey**\n    *   [추천 이유] 라이트 그레이 컬러는 부드럽고 차분한 느낌을 주어 다양한 톤의 옷과 조화롭게 어울립니다.\n    *   [추천 이유] 유기농 코튼 저지 소재의 편안함과 밑단의 스냅 버튼은 일상생활에서 편의성을 제공합니다.\n    *   [추천 이유] 3개 묶음 구성은 실용적이며, 기본 아이템으로 활용하기에 매우 좋습니다.'},
 {'input': '10. 상품명: Hair Ring, 카테고리: Hair string, 색상: Gold, 설명: Hair clip in the shape of a metal ring that opens and has a hair elastic inside.',
  'output': '10. **상품명: Hair Ring, 카테고리: Hair string, 색상: Gold**\n    *   [추천 이유] 골드 컬러의 링 모양 헤어 클립은 심플하면서도 세련된 포인트를 줄 수 있는 아이템입니다.\n    *   [추천 이유] 헤어 엘라스틱이 내장되어 있어 실용적이며, 별도의 머리끈 없이도 깔끔하게 머리를 묶을 수 있습니다.\n    *   [추천 이유] 독특한 디자인으로 평범한 헤어스타일에도 특별함을 더해주어 개성을 표현하기 좋습니다.'},
 {'input': '1. 상품명: Hair Ring, 카테고리: Hair string, 색상: Silver, 설명: Hair clip in the shape of a metal ring that opens and has a hair elastic inside.',
  'output': '1.  **상품명: Hair Ring, 카테고리: Hair string, 색상: Silver, 설명: Hair clip in the shape of a metal ring that opens and has a hair elastic inside.**\n    *   **추천 이유:** 이 헤어링은 심플하면서도 세련된 디자인으로 어떤 스타일에도 포인트를 줄 수 있습니다. 금속 링 모양의 클립 안에 헤어 엘라스틱이 내장되어 있어 실용성까지 갖춘 아이템입니다.'},
 {'input': '2. 상품명: 200 den 1p leggings, 카테고리: Leggings/Tights, 색상: Black, 설명: Opaque matt leggings with an elasticated waist. 200 denier.',
  'output': '2.  **상품명: 200 den 1p leggings, 카테고리: Leggings/Tights, 색상: Black, 설명: Opaque matt leggings with an elasticated waist. 200 denier.**\n    *   **추천 이유:** 200 데니어의 두께감 있는 소재는 보온성과 함께 하체를 안정적으로 잡아주어 날씬해 보이는 효과를 줍니다. 무광 블랙 색상은 어떤 의상과도 매치하기 쉬우며, 밴딩 허리 디자인으로 편안하게 착용 가능합니다.'},
 {'input': '3. 상품명: 6P SS BODY, 카테고리: Bodysuit, 색상: White, 설명: Short-sleeved bodysuits in organic cotton jersey with press-studs at the crotch.',
  'output': '3.  **상품명: 6P SS BODY, 카테고리: Bodysuit, 색상: White, 설명: Short-sleeved bodysuits in organic cotton jersey with press-studs at the crotch.**\n    *   **추천 이유:** 유기농 면 소재의 바디슈트는 부드러운 촉감으로 민감한 피부에도 적합하며, 짧은 소매 디자인은 단독으로 입거나 레이어드하기 좋습니다. 가랑이 부분의 스냅 버튼은 옷을 갈아입거나 기저귀를 교체할 때 편리함을 제공합니다.'},
 {'input': '4. 상품명: Nouvelle 1p Stay Up, 카테고리: Leggings/Tights, 색상: Black, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.',
  'output': '4.  **상품명: Nouvelle 1p Stay Up, 카테고리: Leggings/Tights, 색상: Black, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.**\n    *   **추천 이유:** 20 데니어의 얇은 두께감과 세미 글로시한 소재는 다리를 매끈하고 길어 보이게 연출해 줍니다. 허벅지 상단의 넓은 레이스 트리밍과 실리콘 처리는 흘러내림 없이 안정적인 착용감을 제공하며, 고급스러운 느낌을 더합니다.'},
 {'input': '5. 상품명: Nouvelle 1p Stay Up, 카테고리: Socks, 색상: Beige, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.',
  'output': '5.  **상품명: Nouvelle 1p Stay Up, 카테고리: Socks, 색상: Beige, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.**\n    *   **추천 이유:** 베이지 색상의 스테이업은 다리 본연의 색감을 살려주면서도 생기를 더해주어 자연스럽고 세련된 연출이 가능합니다. 얇은 두께와 고급스러운 레이스 디테일은 스커트나 원피스 스타일에 우아함을 더해줄 것입니다.'},
 {'input': '6. 상품명: THOMPSON woven sport pants, 카테고리: Trousers, 색상: Black, 설명: Running trousers in fast-drying, breathable functional fabric with elastication and a concealed drawstring at the waist. Mesh-lined side pockets, a concealed key pocket in the waistband, a zip at the hems, and reflective details. Regular fit.',

In [40]:
import re
import pandas as pd

def parse_text_to_df(text: str) -> pd.DataFrame:
    # 1. 아이템 단위 split (1., 2., ...)
    items = re.split(r'\n\d+\.\s', text)
    items = [i.strip() for i in items if i.strip()]

    parsed = []

    # 2. 각 아이템 파싱
    for item in items:
        fields = {}

        parts = item.split(', ')
        for p in parts:
            if ': ' not in p:
                continue
            key, value = p.split(': ', 1)  # 설명에 ':' 있어도 안전
            fields[key.strip()] = value.strip()

        parsed.append(fields)

    # 3. DataFrame 변환
    df = pd.DataFrame(parsed)

    return df

In [42]:
with open("training_data.json", "r", encoding="utf-8") as f:
    text = f.read()

df = parse_text_to_df(text)

print(df.head())

  [\n  {\n    "input"    카테고리  \
0  "1. 상품명: Strap top  Hoodie

                                                  색상     설명  \
0  Black**\n    *   블랙 색상의 숏 패딩 재킷은 어떤 스타일에도 쉽게 매...  Short

  lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n5. 상품명  \
0                                  OP T-shirt (Idro)

  lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n6. 상품명  \
0                                  OP T-shirt (Idro)

  lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n7. 상품명  \
0                                20 den 1p Stockings

  reinforced trim at the top. Use with a suspender belt. 20 denier.\n8. 상품명  \
0                                20 den 1p Stockings

  reinforced trim at the top. Use with a suspender belt. 20 denier.\n9. 상품명  \
0                          Shape Up 30 den 1p Tights

  thighs and calves while also encouraging blood circulation in the legs. Elasticated waist.",\n    "output"  \
0  "## 패션 추천 전문가의 아이템별 추천 이유\n\n### 1. 상품명: Strap...

   ... and ribbing at the cuffs and hem. Quilted lining.",\n    "output"  \
0  ...  "안녕하세요! 패션 추천 전문가입니다. 고객님의 편안하고 스타일리시한 일상을 위해 ...

  리브 니트 처리된 커프스와 밑단은 활동성을 높여줍니다.\n    *   온종일 집에서 편안하게 휴식을 취하거나 가벼운 활동을 할 때 기분 좋은 착용감을 느끼게 해줄 아이템입니다.\n\n2.  **상품명  \
0                                      FLEECE PYJAMA

  주말 아침 여유로운 시간을 보내기에 완벽한 아이템이 될 것입니다.\n\n3.  **상품명  \
0                                     FLEECE PYJAMA

  선물용으로도 센스 있는 선택이 될 수 있습니다.\n\n4.  **상품명  \
0                           FLEECE PYJAMA

  가볍게 입고 휴식을 취하기에 이만한 아이템이 없습니다.\n\n5.  **상품명  \
0                               FLEECE PYJAMA

  혹은 특별한 날 기분 전환을 위한 홈웨어로 추천합니다.\n\n6.  **상품명 이만한 아이템이 없을 것입니다.\n\n7.  **상품명  \
0                               FLEECE PYJAMA                  FLEECE PYJAMA

  집에서도 사랑스러운 매력을 잃고 싶지 않은 분들께 추천합니다.\n\n8.  **상품명  \
0                                   FLEECE PYJAMA

  가벼운 집안일을 할 때에도 흐트러짐 없이 깔끔한 모습을 유지할 수 있습니다.\n\n9.  **상품명  \
0                                      FLEECE PYJAMA

  이 점프수트는 최고의 선택이 될 것입니다.\n\n10. **상품명
0                 Mr Harrington w/hood

[1 rows x 120 columns]

In [43]:
df

,"[\n {\n ""input""",카테고리,색상,설명,lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n5. 상품명,lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n6. 상품명,lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n7. 상품명,reinforced trim at the top. Use with a suspender belt. 20 denier.\n8. 상품명,reinforced trim at the top. Use with a suspender belt. 20 denier.\n9. 상품명,"thighs and calves while also encouraging blood circulation in the legs. Elasticated waist."",\n ""output""",...,"and ribbing at the cuffs and hem. Quilted lining."",\n ""output""",리브 니트 처리된 커프스와 밑단은 활동성을 높여줍니다.\n * 온종일 집에서 편안하게 휴식을 취하거나 가벼운 활동을 할 때 기분 좋은 착용감을 느끼게 해줄 아이템입니다.\n\n2. **상품명,주말 아침 여유로운 시간을 보내기에 완벽한 아이템이 될 것입니다.\n\n3. **상품명,선물용으로도 센스 있는 선택이 될 수 있습니다.\n\n4. **상품명,가볍게 입고 휴식을 취하기에 이만한 아이템이 없습니다.\n\n5. **상품명,혹은 특별한 날 기분 전환을 위한 홈웨어로 추천합니다.\n\n6. **상품명,이만한 아이템이 없을 것입니다.\n\n7. **상품명,집에서도 사랑스러운 매력을 잃고 싶지 않은 분들께 추천합니다.\n\n8. **상품명,가벼운 집안일을 할 때에도 흐트러짐 없이 깔끔한 모습을 유지할 수 있습니다.\n\n9. **상품명,이 점프수트는 최고의 선택이 될 것입니다.\n\n10. **상품명
0,"""1. 상품명: Strap top",Hoodie,Black**\n * 블랙 색상의 숏 패딩 재킷은 어떤 스타일에도 쉽게 매...,Short,OP T-shirt (Idro),OP T-shirt (Idro),20 den 1p Stockings,20 den 1p Stockings,Shape Up 30 den 1p Tights,"""## 패션 추천 전문가의 아이템별 추천 이유\n\n### 1. 상품명: Strap...",...,"""안녕하세요! 패션 추천 전문가입니다. 고객님의 편안하고 스타일리시한 일상을 위해 ...",FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,FLEECE PYJAMA,Mr Harrington w/hood

In [ ]:
fine_tuning_data = []

for batch in training_data:
    input_items = batch['input'].split('\n')
    output_text = batch['output']
    
    # \n숫자. 로 분리
    sections = re.split(r'\n(?=\d+\.)', output_text)
    sections = [s.strip() for s in sections if s.strip()]
    
    # 첫 번째 헤더 제거
    sections = [s for s in sections if not s.startswith('##')]
    
    input_items = [line.strip() for line in input_items if line.strip()]
    
    for i, section in enumerate(sections):
        if i < len(input_items):
            fine_tuning_data.append({
                "input": input_items[i],
                "output": section
            })

print(f"파인튜닝 데이터 수: {len(fine_tuning_data)}")
print(fine_tuning_data[0])

파인튜닝 데이터 수: 70
{'input': '1. 상품명: 200 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Opaque matt tights. 200 denier.', 'output': '1.  **200 den 1p Tights (Black)**\n    *   200 데니어의 두께감과 불투명한 매트한 질감으로 보온성은 물론, 매끈하고 깔끔한 하체 라인을 연출하는 데 탁월합니다.\n    *   블랙 컬러는 어떤 의상에도 매치하기 쉬워 활용도가 높으며, 겨울철 스커트나 원피스 착용 시 필수적인 아이템입니다.'}

In [7]:
import json
from google import genai
from google.genai import types
with open("config.json") as f:
    config = json.load(f)


from google import genai

client = genai.Client(api_key=config['GEMINI_API_KEY'])

#response = client.models.generate_content(
#    model="gemini-2.0-flash-lite",
#    contents="안녕",
#    config=types.GenerateContentConfig(
#        http_options=types.HttpOptions(timeout=15000)
#    )
#)

#print(response.text)

response = client.models.generate_content(
    model='gemini-3.1-flash-lite-preview',
    contents="안녕",
    config=types.GenerateContentConfig(
        http_options=types.HttpOptions(timeout=15000)
    )
)

print(response.text)

#genai.configure(api_key=config['GEMINI_API_KEY'])
#model = genai.GenerativeModel('gemini-3.1-flash-lite-preview')
#response = model.generate_content("안녕",request_options={"timeout": 15})
#print(response.text)

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [10]:
import time
import json
import google.generativeai as genai
with open("config.json") as f:
    config = json.load(f)

genai.configure(api_key=config['GEMINI_API_KEY'])


model = genai.GenerativeModel('gemini-2.5-flash-lite')



def generate_korean_reasons_batch(items_batch):
    items_text = "\n".join([
        f"{i+1}. 상품명: {item['prod_name']}, 카테고리: {item['product_type_name']}, 색상: {item['colour_group_name']}, 설명: {item['detail_desc']}"
        for i, item in enumerate(items_batch)
    ])
    
    prompt = f"""당신은 패션 추천 전문가입니다. 반드시 한국어로만 답변하세요.

다음 패션 아이템들 각각을 추천하는 이유를 한국어로 2-3문장씩 작성해주세요.

{items_text}

반드시 아래 형식으로만 답하세요. 번호와 추천 이유 외에 제목, 설명, 부가 텍스트는 절대 추가하지 마세요:
1. 추천 이유
2. 추천 이유
3. 추천 이유"""

    response = model.generate_content(prompt)
    return {
        "input": items_text,
        "output": response.text
    }

training_data = []
batch_size = 25

for i in range(0, 400, batch_size):
    batch = [articles.iloc[j] for j in range(i, min(i+batch_size, len(articles)))]
    result = generate_korean_reasons_batch(batch)
    training_data.append(result)
    time.sleep(4)
    if (i // batch_size + 1) % 4 == 0:
        print(f"{i + batch_size}/1000 완료")

with open('training_data.json', 'w', encoding='utf-8') as f:
    json.dump(training_data, f, ensure_ascii=False, indent=2)

print("완료!")

100/1000 완료

InternalServerError: 500 An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting

In [16]:
# 100개 아이템 텍스트로 만들기
items_text = "\n".join([
    f"{i+1}. 상품명: {articles.iloc[i]['prod_name']}, 카테고리: {articles.iloc[i]['product_type_name']}, 색상: {articles.iloc[i]['colour_group_name']}, 설명: {articles.iloc[i]['detail_desc']}"
    for i in range(100)
])

with open('items_for_gpt.txt', 'w', encoding='utf-8') as f:
    f.write(items_text)

print("저장 완료!")
print(items_text[:500])

저장 완료!
1. 상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.
2. 상품명: Strap top, 카테고리: Vest top, 색상: White, 설명: Jersey top with narrow shoulder straps.
3. 상품명: Strap top (1), 카테고리: Vest top, 색상: Off White, 설명: Jersey top with narrow shoulder straps.
4. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Black, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-an

In [19]:
prompt_header = """당신은 패션 추천 전문가입니다. 반드시 한국어로만 답변하세요.

다음 패션 아이템들 각각을 추천하는 이유를 한국어로 2-3문장씩 작성해주세요.

"""

prompt_footer = """

반드시 아래 형식으로만 답하세요. 번호와 추천 이유 외에 제목, 설명, 부가 텍스트는 절대 추가하지 마세요:
1. 추천 이유
2. 추천 이유
..."""

for batch_num in range(20):
    start = batch_num * 50
    
    items_text = "\n".join([
        f"{i+1}. 상품명: {articles.iloc[start+i]['prod_name']}, 카테고리: {articles.iloc[start+i]['product_type_name']}, 색상: {articles.iloc[start+i]['colour_group_name']}, 설명: {articles.iloc[start+i]['detail_desc']}"
        for i in range(50)
    ])
    
    full_prompt = prompt_header + items_text + prompt_footer
    
    with open(f'items_batch_{batch_num+1}.txt', 'w', encoding='utf-8') as f:
        f.write(full_prompt)

print("20개 파일 저장 완료!")

20개 파일 저장 완료!

In [20]:
for batch_num in range(20):
    start = batch_num * 50
    
    items_text = "\n".join([
        f"{i+1}. 상품명: {articles.iloc[start+i]['prod_name']}, 카테고리: {articles.iloc[start+i]['product_type_name']}, 색상: {articles.iloc[start+i]['colour_group_name']}, 설명: {articles.iloc[start+i]['detail_desc']}"
        for i in range(50)
    ])
    
    full_prompt = ""
    
    with open(f'answer_{batch_num+1}.txt', 'w', encoding='utf-8') as f:
        f.write(full_prompt)

print("20개 파일 저장 완료!")

20개 파일 저장 완료!

In [21]:
from google import genai
import time
with open("config.json") as f:
    config = json.load(f)

client = genai.Client(api_key=config['GEMINI_API_KEY'])

def call_gemini(prompt: str):
    response = client.models.generate_content(
        model="gemini-3.1-flash-lite-preview",  # ✅ 이게 핵심
        contents=prompt
    )
    return response.text


print(call_gemini("CLIP이 뭐야?"))

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [14]:
models = client.models.list()

for m in models:
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview

In [ ]:
prompts = [
    "상품 추천 이유 만들어줘",
    "이 상품 카테고리 분류해줘",
    "설명 요약해줘"
]

for p in prompts:
    print(call_gemini(p))
    time.sleep(5)  # RPM 15 기준 안전

In [11]:
training_data

[{'input': '1. 상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps.\n2. 상품명: Strap top, 카테고리: Vest top, 색상: White, 설명: Jersey top with narrow shoulder straps.\n3. 상품명: Strap top (1), 카테고리: Vest top, 색상: Off White, 설명: Jersey top with narrow shoulder straps.\n4. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Black, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n5. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: White, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n6. 상품명: OP T-shirt (Idro), 카테고리: Bra, 색상: Light Beige, 설명: Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort.\n7. 상품명: 20 den 1p Stockings, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n8. 상품명: 20 den 1p Stockings, 카테고리: Socks, 색상: Beige, 설명: Semi shiny nylon stockings with a wide, reinforced trim at the top. Use with a suspender belt. 20 denier.\n9. 상품명: Shape Up 30 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: Tights with built-in support to lift the bottom. Black in 30 denier and light amber in 15 denier.\n10. 상품명: Support 40 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Semi shiny tights that shape the tummy, thighs and calves while also encouraging blood circulation in the legs. Elasticated waist.\n11. 상품명: 200 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Opaque matt tights. 200 denier.\n12. 상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Grey, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.\n13. 상품명: SWEATSHIRT  OC, 카테고리: Sweater, 색상: Light Blue, 설명: Sweatshirt in soft organic cotton with a  press-stud on one shoulder (sizes 12-18 months and 18-24 months without a press-stud). Brushed inside.\n14. 상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: White, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.\n15. 상품명: Alice BANDEAU 2-p, 카테고리: Bra, 색상: Light Grey, 설명: Two soft bandeau bras in soft jersey with side support and a silicone trim at the top.\n16. 상품명: Frugan longsleeve, 카테고리: Top, 색상: Dark Blue, 설명: Fitted top in soft stretch jersey with a wide neckline and long sleeves.\n17. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n18. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n19. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n20. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Grey, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n21. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Pink, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n22. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Black, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n23. 상품명: Jerry jogger bottoms, 카테고리: Trousers, 색상: Dark Blue, 설명: Trousers in sweatshirt fabric with an elasticated drawstring waist, side pockets, a back pocket and ribbed hems. Soft brushed inside.\n24. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.\n25. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Black, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
  'output': '1. 기본템으로 활용도가 높아 어디에나 매치하기 좋습니다. 얇은 스트랩으로 시원하면서도 여성스러운 느낌을 더해줍니다.\n2. 어떤 색상의 옷과도 잘 어울리는 화이트 스트랩 탑은 활용도가 높습니다. 시원하고 산뜻한 느낌을 연출하기에 좋습니다.\n3. 오프화이트 컬러는 부드럽고 차분한 분위기를 연출합니다. 다른 컬러와 믹스매치하여 세련된 스타일을 완성할 수 있습니다.\n4. 노출이 있는 의상에도 깔끔하게 착용 가능하며, 편안한 착용감과 섬세한 실루엣을 연출해 줍니다.\n5. 깔끔하고 단정한 스타일을 선호하는 분들에게 추천하며, 베이직한 디자인으로 어떤 옷에도 자연스럽게 어울립니다.\n6. 스킨톤에 가까운 라이트 베이지 컬러는 옷 위로 티 나지 않아 활용도가 높습니다. 답답함 없이 편안한 착용감을 제공합니다.\n7. 20 데니어의 얇은 두께감으로 스타킹의 느낌을 살리면서도, 섬세한 룩을 완성하는 데 도움을 줍니다.\n8. 베이지 컬러는 다리를 자연스럽고 매끈하게 보이게 하여 여성스러운 매력을 더합니다. 20 데니어의 얇은 두께감이 더욱 고급스러운 느낌을 줍니다.\n9. 힙업 효과와 함께 탄탄한 다리 라인을 연출하여 자신감 있는 스타일을 완성해 줍니다. 30 데니어의 적당한 두께감으로 활동성을 높여줍니다.\n10. 복부, 허벅지, 종아리 라인을 매끄럽게 잡아주어 슬림한 실루엣을 연출합니다. 혈액순환에도 도움을 주어 건강까지 챙길 수 있습니다.\n11. 200 데니어의 두꺼운 두께감으로 따뜻하면서도 보온성을 높여줍니다. 무광의 매트한 질감으로 고급스러운 느낌을 줍니다.\n12. 부드러운 오가닉 코튼 소재로 아이의 피부에 자극 없이 편안하게 착용 가능합니다. 어깨 스냅 버튼으로 아이 옷 입히기가 편리합니다.\n13. 아이보리 컬러는 깨끗하고 부드러운 이미지를 연출하며, 어떤 하의와도 잘 어울립니다. 활동적인 아이에게 편안함을 선사합니다.\n14. 밴드 형태의 디자인으로 속옷 라인이 드러나지 않아 깔끔하며, 가볍고 편안한 착용감을 제공합니다.\n15. 라이트 그레이 컬러는 세련되고 모던한 느낌을 주며, 데일리로 착용하기 좋습니다. 부드러운 소재가 편안함을 더해줍니다.\n16. 슬림하게 몸에 핏되어 날씬해 보이는 효과를 주며, 넓은 네크라인으로 여성스러움을 강조할 수 있습니다.\n17. 부드러운 기모 안감으로 포근하고 편안한 착용감을 선사하며, 밴딩 허리와 조임 스트링으로 활동성을 높여줍니다.\n18. 캐주얼한 디자인으로 어떤 상의와도 매치하기 쉬우며, 편안한 착용감으로 데일리룩으로 활용하기 좋습니다.\n19. 베이직한 블랙 컬러는 어떤 스타일에도 매치하기 용이하며, 편안한 실루엣으로 활동성을 높여줍니다.\n20. 다크 그레이 컬러는 세련되고 시크한 느낌을 주며, 캐주얼룩부터 꾸민 듯 안 꾸민 듯한 룩까지 다양하게 연출 가능합니다.\n21. 산뜻하고 발랄한 핑크 컬러는 개성 있는 포인트를 주기에 좋으며, 부드러운 소재로 편안하게 착용 가능합니다.\n22. 힙하면서도 편안한 조거 팬츠는 다양한 상의와 매치하여 스트릿 패션을 완성하기 좋습니다.\n23. 짙은 네이비 컬러는 차분하면서도 세련된 느낌을 주며, 데일리로 편안하게 착용하기 좋습니다.\n24. 허리 부분의 넓은 패널이 복부를 편안하게 감싸주어 안정감 있고 슬림한 실루엣을 연출합니다.\n25. 부드러운 저지 소재와 편안한 착용감으로 데일리로 활용하기 좋으며, 오가닉 코튼으로 제작되어 피부에도 순합니다.'},
 {'input': '1. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Red, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.\n2. 상품명: Babette long, 카테고리: Leggings/Tights, 색상: Dark Grey, 설명: Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.\n3. 상품명: Control Top 50 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: 50 denier tights with reinforcement at the top for a shaping effect on the tummy and thighs.\n4. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Black, 설명: Plastic hair claws. Width 3.5 cm.\n5. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Greyish Beige, 설명: Plastic hair claws. Width 3.5 cm.\n6. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Light Orange, 설명: Plastic hair claws. Width 3.5 cm.\n7. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Silver, 설명: Plastic hair claws. Width 3.5 cm.\n8. 상품명: 2p Claw, 카테고리: Hair clip, 색상: Gold, 설명: Plastic hair claws. Width 3.5 cm.\n9. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Black, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.\n10. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: White, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.\n11. 상품명: Pirate Leggings (1), 카테고리: Leggings/Tights, 색상: Grey, 설명: 3/4-length leggings in stretch jersey with an elasticated waist.\n12. 상품명: Black Umbrella, 카테고리: Umbrella, 색상: Black, 설명: Umbrella with a telescopic handle and matching cover. Length 23 cm folded.\n13. 상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: White, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.\n14. 상품명: Velour pyjama, 카테고리: Pyjama jumpsuit/playsuit, 색상: Light Pink, 설명: Velour pyjamas with an appliqué detail at the front and on the feet, and press-studs along one side and leg.\n15. 상품명: Mama 100 den 1p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Matt tights with an elasticated waist and extra space for a growing tummy. 100 denier.\n16. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n17. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n18. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: White, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n19. 상품명: Dorian l/s basic, 카테고리: Top, 색상: Black, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n20. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Blue, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n21. 상품명: Dorian l/s basic, 카테고리: Sweater, 색상: Dark Grey, 설명: Long-sleeved sports top in fast-drying, breathable functional fabric with overlocked seams for optimum comfort. Some of the polyester content of the top is recycled.\n22. 상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.\n23. 상품명: Tanktop body white 3PACK, 카테고리: Bodysuit, 색상: White, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.\n24. 상품명: 3P TANKTOP BODY, 카테고리: Bodysuit, 색상: Light Grey, 설명: Sleeveless bodysuits in soft organic cotton jersey with press-studs at the crotch.\n25. 상품명: Hair Ring, 카테고리: Hair string, 색상: Gold, 설명: Hair clip in the shape of a metal ring that opens and has a hair elastic inside.',
  'output': '1. 부드러운 저지 소재와 허리의 넓은 패널 디자인으로 편안하게 착용할 수 있습니다. 임산부에게도 편안한 착용감을 제공하며, 오가닉 코튼 소재로 민감한 피부에도 안심하고 입을 수 있습니다.\n2. 부드러운 저지 소재와 허리의 넓은 패널 디자인으로 편안하게 착용할 수 있습니다. 톤 다운된 다크 그레이 색상은 어떤 스타일에도 자연스럽게 매치되며, 오가닉 코튼 소재로 편안함을 더했습니다.\n3. 50 데니어의 두께감으로 다리 라인을 매끄럽게 잡아주며, 복부와 허벅지를 탄탄하게 보정해주는 효과가 있습니다. 슬림한 실루엣을 연출하고 싶은 날이나 격식 있는 자리에 활용하기 좋습니다.\n4. 심플하면서도 개성 있는 헤어 스타일을 연출하기 좋은 헤어 클립입니다. 3.5cm의 적당한 사이즈로 머리를 깔끔하게 고정해주며, 어떤 착장에도 포인트가 되어줍니다.\n5. 3.5cm의 활용도 높은 사이즈로 머리를 단정하게 정리할 수 있습니다. 은은한 그레이쉬 베이지 색상이 자연스러우면서도 세련된 느낌을 더해줄 것입니다.\n6. 톡톡 튀는 라이트 오렌지 색상이 얼굴빛을 화사하게 만들어주며, 개성 있는 스타일을 연출하고 싶을 때 완벽한 포인트가 됩니다. 3.5cm 사이즈로 머리숱이 많지 않아도 부담 없이 사용할 수 있습니다.\n7. 3.5cm의 컴팩트한 사이즈로 머리를 간편하게 스타일링할 수 있습니다. 시크한 실버 색상이 세련되고 모던한 느낌을 주어 어떤 룩에도 멋스럽게 어울립니다.\n8. 3.5cm의 실용적인 사이즈로 머리를 깔끔하게 정리할 수 있습니다. 고급스러운 골드 색상은 어떤 스타일에든 화려함과 특별함을 더해줄 것입니다.\n9. 3/4 길이로 경쾌한 느낌을 주는 레깅스로, 신축성 좋은 저지 소재가 편안한 착용감을 선사합니다. 캐주얼한 티셔츠나 맨투맨과 함께 매치하여 활동적인 룩을 연출하기 좋습니다.\n10. 3/4 길이의 화이트 레깅스는 산뜻하고 밝은 느낌을 줍니다. 다양한 상의와 매치하기 좋으며, 특히 여름철 시원하고 스타일리시한 코디를 완성하는 데 유용합니다.\n11. 3/4 길이의 그레이 레깅스는 편안하면서도 차분한 스타일을 연출하기 좋습니다. 부드러운 저지 소재와 엘라스틱 허리 밴드가 활동성을 높여주어 데일리룩으로 활용하기 좋습니다.\n12. 23cm로 접었을 때 컴팩트하여 휴대하기 좋은 우산입니다. 튼튼한 블랙 색상은 어떤 상황에서도 실용적이며, 함께 제공되는 커버로 깔끔하게 보관할 수 있습니다.\n13. 부드러운 벨루어 소재와 귀여운 아플리케이션 디테일이 돋보이는 파자마입니다. 똑딱이 단추로 입고 벗기 편리하며, 편안한 잠옷으로 집에서의 휴식을 더욱 아늑하게 만들어줍니다.\n14. 사랑스러운 라이트 핑크 색상의 벨루어 파자마는 포근하고 부드러운 느낌을 줍니다. 아플리케이션 디테일과 편리한 똑딱이 단추로 편안한 수면 시간을 선사합니다.\n15. 100 데니어의 두께감으로 보온성이 뛰어나며, 늘어나는 배를 위한 넉넉한 공간이 특징입니다. 임산부에게 최적화된 디자인으로 편안하고 안정감 있는 착용감을 제공합니다.\n16. 기능성 스포츠웨어로 땀을 빠르게 흡수하고 건조하는 소재를 사용하여 쾌적함을 유지시켜 줍니다. 오버록 처리된 솔기는 움직임이 많은 운동 중에도 편안함을 더하며, 재활용 폴리에스터를 사용하여 지속가능성까지 생각했습니다.\n17. 땀을 빠르게 흡수하고 통기성이 좋은 기능성 소재로 제작되어 운동 시 쾌적함을 유지시켜 줍니다. 오버록 솔기로 마찰을 최소화하고, 재활용 폴리에스터를 사용하여 친환경적인 가치까지 담았습니다.\n18. 땀을 잘 흡수하고 빠르게 건조하는 기능성 소재로 제작되어 언제나 쾌적한 착용감을 선사합니다. 산뜻한 화이트 색상은 다양한 운동복과 매치하기 좋으며, 편안한 오버록 솔기가 활동성을 높여줍니다.\n19. 땀을 빠르게 흡수하고 통기성이 뛰어난 기능성 소재로 제작되어 운동이나 일상생활에서 쾌적함을 유지시켜 줍니다. 재활용 폴리에스터를 사용하여 지속가능한 패션을 실천할 수 있습니다.\n20. 땀을 빠르게 흡수하고 통기성이 좋은 기능성 소재로 제작되어 운동 시 최상의 퍼포먼스를 낼 수 있도록 도와줍니다. 차분한 다크 블루 색상은 어떤 운동복과도 잘 어울리며, 편안한 착용감을 제공합니다.\n21. 땀을 빠르게 흡수하고 건조하는 기능성 소재와 편안한 오버록 솔기가 결합된 상의입니다. 재활용 폴리에스터를 사용하여 환경을 생각하는 동시에 쾌적하고 활동적인 시간을 보낼 수 있도록 도와줍니다.\n22. 부드러운 오가닉 코튼 소재로 제작되어 피부에 자극 없이 편안하게 착용할 수 있습니다. 어깨끈이 있는 탱크탑 스타일로 단독으로 입거나 이너웨어로 활용하기 좋으며, 밑단의 똑딱이 단추로 편리성을 더했습니다.\n23. 부드러운 오가닉 코튼 소재와 편안한 탱크탑 스타일의 디자인이 특징입니다. 밑단의 똑딱이 단추로 기저귀 교체가 용이하며, 활동량이 많은 아기들에게도 적합합니다.\n24. 부드러운 오가닉 코튼 소재로 제작되어 민감한 피부에도 편안하게 착용할 수 있습니다. 라이트 그레이 색상은 어떤 옷과도 자연스럽게 어울리며, 밑단의 똑딱이 단추로 편리하게 사용할 수 있습니다.\n25. 머리에 포인트를 주기 좋은 독특한 디자인의 헤어 클립입니다. 반지 모양의 헤어 클립 안에 헤어 고무줄이 내장되어 있어 실용적이며, 스타일링에 재미를 더해줍니다.'},
 {'input': '1. 상품명: Hair Ring, 카테고리: Hair string, 색상: Silver, 설명: Hair clip in the shape of a metal ring that opens and has a hair elastic inside.\n2. 상품명: 200 den 1p leggings, 카테고리: Leggings/Tights, 색상: Black, 설명: Opaque matt leggings with an elasticated waist. 200 denier.\n3. 상품명: 6P SS BODY, 카테고리: Bodysuit, 색상: White, 설명: Short-sleeved bodysuits in organic cotton jersey with press-studs at the crotch.\n4. 상품명: Nouvelle 1p Stay Up, 카테고리: Leggings/Tights, 색상: Black, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.\n5. 상품명: Nouvelle 1p Stay Up, 카테고리: Socks, 색상: Beige, 설명: Semi shiny stay-ups with a wide lace trim at the top and silicone on the inside. 20 denier.\n6. 상품명: THOMPSON woven sport pants, 카테고리: Trousers, 색상: Black, 설명: Running trousers in fast-drying, breathable functional fabric with elastication and a concealed drawstring at the waist. Mesh-lined side pockets, a concealed key pocket in the waistband, a zip at the hems, and reflective details. Regular fit.\n7. 상품명: THOMPSON woven sport pants, 카테고리: Trousers, 색상: Dark Grey, 설명: Running trousers in fast-drying, breathable functional fabric with elastication and a concealed drawstring at the waist. Mesh-lined side pockets, a concealed key pocket in the waistband, a zip at the hems, and reflective details. Regular fit.\n8. 상품명: OP Strapless^, 카테고리: Bra, 색상: Black, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n9. 상품명: OP Strapless^, 카테고리: Bra, 색상: Light Beige, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n10. 상품명: OP Strapless^, 카테고리: Bra, 색상: White, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n11. 상품명: OP Strapless^, 카테고리: Bra, 색상: Dark Pink, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n12. 상품명: OP Strapless^, 카테고리: Bra, 색상: Yellowish Brown, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n13. 상품명: OP Strapless^, 카테고리: Bra, 색상: Yellowish Brown, 설명: Strapless bra in microfibre with underwired, padded cups that lift and shape the bust. Silicone trim at the top and a hook-and-eye fastening at the back. Detachable, adjustable shoulder straps and side support.\n14. 상품명: Box 4p Socks, 카테고리: Socks, 색상: Beige, 설명: Semi-matte socks with a short shaft. 20 denier.\n15. 상품명: Box 4p Socks, 카테고리: Unknown, 색상: Black, 설명: Semi-matte socks with a short shaft. 20 denier.\n16. 상품명: Box 4p Kneehighs, 카테고리: Underwear Tights, 색상: Black, 설명: Four pairs of knee highs. 20 denier.\n17. 상품명: Box 4p Kneehighs, 카테고리: Underwear Tights, 색상: Beige, 설명: Four pairs of knee highs. 20 denier.\n18. 상품명: Box 4p Tights, 카테고리: Underwear Tights, 색상: Black, 설명: Matt tights with an elasticated waist. 20 denier.\n19. 상품명: Box 4p Tights, 카테고리: Leggings/Tights, 색상: Beige, 설명: Matt tights with an elasticated waist. 20 denier.\n20. 상품명: Slim Cheapo 79, 카테고리: Trousers, 색상: Blue, 설명: 5-pocket slim-fit jeans in washed denim with an adjustable elasticated waist, zip fly with a press-stud and slim legs.\n21. 상품명: Connor pants, 카테고리: Trousers, 색상: Black, 설명: Sports trousers in fast-drying fabric made from recycled polyester with an elasticated drawstring waist, side pockets and tapered legs. Regular fit.\n22. 상품명: Anton sport pant, 카테고리: Trousers, 색상: Black, 설명: Sports trousers in fast-drying fabric made from recycled polyester with an elasticated drawstring waist, side pockets and tapered legs. Regular fit.\n23. 상품명: Anton sport pant, 카테고리: Trousers, 색상: Black, 설명: Sports trousers in fast-drying fabric made from recycled polyester with an elasticated drawstring waist, side pockets and tapered legs. Regular fit.\n24. 상품명: Highwaist 30 den 1p Tights, 카테고리: Leggings/Tights, 색상: Black, 설명: High-waisted tights that lift the bum and shape the waist and thighs. 30 denier.\n25. 상품명: 3p Sneaker Socks, 카테고리: Socks, 색상: Black, 설명: Short, fine-knit socks designed to be hidden by your shoes with a silicone trim at the back of the heel to keep them in place.',
  'output': '1.  독특한 링 디자인이 헤어 스타일에 포인트를 더해주며, 내장된 헤어 슈슈로 간편하게 머리를 묶을 수 있습니다. 은은한 실버 색상은 어떤 의상에도 세련되게 어울립니다.\n2.  200 데니아의 두께감과 불투명한 무광 질감으로 레깅스만으로도 안정감 있는 스타일을 연출할 수 있습니다. 탄력 있는 허리 밴드는 편안한 착용감을 선사합니다.\n3.  매일 입어도 질리지 않는 베이직한 흰색의 반팔 바디수트는 어떤 하의와도 매치하기 좋습니다. 부드러운 오가닉 코튼 소재와 편안한 똑딱이 단추로 아이에게 편안함을 선사합니다.\n4.  20 데니아의 얇고 은은한 광택이 고급스러운 느낌을 주는 스테이업 스타킹입니다. 넓은 레이스 트리밍과 실리콘 처리가 흘러내림 없이 편안하게 착용 가능합니다.\n5.  20 데니아의 얇고 은은한 광택이 고급스러운 느낌을 주는 스테이업 스타킹입니다. 넓은 레이스 트리밍과 실리콘 처리가 흘러내림 없이 편안하게 착용 가능합니다.\n6.  땀이 빠르게 마르고 통기성이 좋은 기능성 소재로 제작되어 운동 시 쾌적함을 유지해 줍니다. 허리의 편안한 엘라스틱 밴드와 스트링, 밑단의 지퍼 디테일이 활동성을 높여줍니다.\n7.  땀이 빠르게 마르고 통기성이 좋은 기능성 소재로 제작되어 운동 시 쾌적함을 유지해 줍니다. 허리의 편안한 엘라스틱 밴드와 스트링, 밑단의 지퍼 디테일이 활동성을 높여줍니다.\n8.  스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n9.  스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n10. 스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n11. 스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n12. 스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n13. 스트랩이 없어 깔끔한 넥 라인을 연출할 수 있으며, 밑단의 실리콘 처리로 안정감 있게 고정됩니다. 탈부착 가능한 스트랩으로 다양한 연출이 가능하여 활용도가 높습니다.\n14. 은은한 광택과 짧은 기장으로 데일리로 착용하기 좋으며, 편안한 착용감을 제공합니다. 다양한 신발과 매치하여 깔끔한 룩을 완성할 수 있습니다.\n15. 은은한 광택과 짧은 기장으로 데일리로 착용하기 좋으며, 편안한 착용감을 제공합니다. 다양한 신발과 매치하여 깔끔한 룩을 완성할 수 있습니다.\n16. 20 데니아의 얇은 두께로 답답함 없이 착용 가능하며, 네이비 색상은 시크한 무드를 더해줍니다. 4족 세트로 구성되어 있어 다양하게 활용하기 좋습니다.\n17. 20 데니아의 얇은 두께로 답답함 없이 착용 가능하며, 베이지 색상은 부드러운 느낌을 줍니다. 4족 세트로 구성되어 있어 다양하게 활용하기 좋습니다.\n18. 20 데니아의 얇고 부드러운 소재와 허리 밴드로 편안한 착용감을 자랑합니다. 어떤 의상에도 매치하기 좋은 기본 검정 타이츠입니다.\n19. 20 데니아의 얇고 부드러운 소재와 허리 밴드로 편안한 착용감을 자랑합니다. 어떤 의상에도 매치하기 좋은 기본 베이지 타이츠입니다.\n20. 슬림한 핏과 워싱 데님 소재로 스타일리시함을 더해주며, 조절 가능한 허리 밴드로 편안하게 착용할 수 있습니다. 5포켓 디자인으로 실용성까지 갖춘 매력적인 아이템입니다.\n21. 재활용 폴리에스터 소재와 땀이 잘 마르는 기능성으로 쾌적함을 유지해주며, 테이퍼드 핏으로 세련된 실루엣을 연출합니다. 조절 가능한 허리 밴드로 편안한 착용감을 선사합니다.\n22. 재활용 폴리에스터 소재와 땀이 잘 마르는 기능성으로 쾌적함을 유지해주며, 테이퍼드 핏으로 세련된 실루엣을 연출합니다. 조절 가능한 허리 밴드로 편안한 착용감을 선사합니다.\n23. 재활용 폴리에스터 소재와 땀이 잘 마르는 기능성으로 쾌적함을 유지해주며, 테이퍼드 핏으로 세련된 실루엣을 연출합니다. 조절 가능한 허리 밴드로 편안한 착용감을 선사합니다.\n24. 하이웨이스트 디자인으로 허리와 힙 라인을 잡아주어 더욱 슬림하고 볼륨감 있는 실루엣을 연출할 수 있습니다. 30 데니아의 적당한 두께로 비침 없이 편안하게 착용 가능합니다.\n25. 신발 안으로 들어가 보이지 않아 깔끔하며, 뒷꿈치 실리콘 처리가 흘러내림을 방지해 줍니다. 얇은 니트 소재로 발이 편안하며, 운동화에 매치하기 좋습니다.'},

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [2]:
from datasets import load_dataset
dataset = load_dataset("beomi/KoAlpaca-v1.1a")
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['instruction', 'output', 'url'],
        num_rows: 21155
    })
})

In [3]:
print(dataset)
print(dataset['train'][0])

DatasetDict({
    train: Dataset({
        features: ['instruction', 'output', 'url'],
        num_rows: 21155
    })
})
{'instruction': '양파는 어떤 식물 부위인가요? 그리고 고구마는 뿌리인가요?', 'output': '양파는 잎이 아닌 식물의 줄기 부분입니다. 고구마는 식물의 뿌리 부분입니다. \n\n식물의 부위의 구분에 대해 궁금해하는 분이라면 분명 이 질문에 대한 답을 찾고 있을 것입니다. 양파는 잎이 아닌 줄기 부분입니다. 고구마는 다른 질문과 답변에서 언급된 것과 같이 뿌리 부분입니다. 따라서, 양파는 식물의 줄기 부분이 되고, 고구마는 식물의 뿌리 부분입니다.\n\n 덧붙이는 답변: 고구마 줄기도 볶아먹을 수 있나요? \n\n고구마 줄기도 식용으로 볶아먹을 수 있습니다. 하지만 줄기 뿐만 아니라, 잎, 씨, 뿌리까지 모든 부위가 식용으로 활용되기도 합니다. 다만, 한국에서는 일반적으로 뿌리 부분인 고구마를 주로 먹습니다.', 'url': 'https://kin.naver.com/qna/detail.naver?d1id=11&dirId=1116&docId=55320268'}

In [4]:
def format_data(item):
    return {"text": f"### 지시사항:\n{item['instruction']}\n\n### 답변:\n{item['output']}"}

train_dataset = dataset['train'].map(format_data, remove_columns=['instruction', 'output', 'url'])
print(train_dataset[0])

{'text': '### 지시사항:\n양파는 어떤 식물 부위인가요? 그리고 고구마는 뿌리인가요?\n\n### 답변:\n양파는 잎이 아닌 식물의 줄기 부분입니다. 고구마는 식물의 뿌리 부분입니다. \n\n식물의 부위의 구분에 대해 궁금해하는 분이라면 분명 이 질문에 대한 답을 찾고 있을 것입니다. 양파는 잎이 아닌 줄기 부분입니다. 고구마는 다른 질문과 답변에서 언급된 것과 같이 뿌리 부분입니다. 따라서, 양파는 식물의 줄기 부분이 되고, 고구마는 식물의 뿌리 부분입니다.\n\n 덧붙이는 답변: 고구마 줄기도 볶아먹을 수 있나요? \n\n고구마 줄기도 식용으로 볶아먹을 수 있습니다. 하지만 줄기 뿐만 아니라, 잎, 씨, 뿌리까지 모든 부위가 식용으로 활용되기도 합니다. 다만, 한국에서는 일반적으로 뿌리 부분인 고구마를 주로 먹습니다.'}

In [5]:

from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
import torch

tokenizer = AutoTokenizer.from_pretrained("./qwen")
tokenizer.pad_token = tokenizer.eos_token

# 토크나이징
def tokenize(item):
    result = tokenizer(
        item["text"],
        truncation=True,
        max_length=512,
        padding="max_length"
    )
    result["labels"] = result["input_ids"].copy()
    return result

tokenized_dataset = train_dataset.map(tokenize, remove_columns=["text"])
print(tokenized_dataset)

c:\Users\swson23\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 21155
})

In [6]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.6.0+cu124
True

In [7]:
import torch
from peft import LoraConfig, get_peft_model

qwen_model = AutoModelForCausalLM.from_pretrained(
    "./qwen",
    torch_dtype=torch.float16,
    device_map="cuda"
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

qwen_model = get_peft_model(qwen_model, lora_config)
qwen_model.config.use_cache = False
qwen_model.print_trainable_parameters()

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

trainable params: 1,843,200 || all params: 3,087,781,888 || trainable%: 0.0597

In [8]:
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

training_args = TrainingArguments(
    output_dir="./qwen_korean",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=100,
    save_steps=500,
    warmup_steps=100,
    report_to="none",
    save_safetensors=False
)

trainer = Trainer(
    model=qwen_model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

#trainer.train()

WARNING:tensorflow:From c:\Users\swson23\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [9]:
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

In [10]:
training_args = TrainingArguments(
    output_dir="./qwen_korean",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=100,
    save_steps=500,
    warmup_steps=100,
    report_to="none",
    save_safetensors=False
)

trainer = Trainer(
    model=qwen_model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

In [11]:
trainer.train(resume_from_checkpoint="./qwen_korean/checkpoint-1000")

TrainOutput(global_step=2645, training_loss=1.0643862170848595, metrics={'train_runtime': 1645.5595, 'train_samples_per_second': 12.856, 'train_steps_per_second': 1.607, 'total_flos': 1.804472272551936e+17, 'train_loss': 1.0643862170848595, 'epoch': 1.0})

In [12]:
qwen_model.save_pretrained("./qwen_korean")
tokenizer.save_pretrained("./qwen_korean")
print("저장 완료!")

저장 완료!

In [17]:
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(
    "./qwen",
    dtype=torch.float16,
    device_map="cuda"
)
korean_model = PeftModel.from_pretrained(base_model, "./qwen_korean")
import torch
torch.cuda.empty_cache()
print(f"VRAM 사용량: {torch.cuda.memory_allocated()/1024**3:.2f}GB")
print(f"VRAM 남은 양: {torch.cuda.memory_reserved()/1024**3:.2f}GB")
prompt = "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps."

messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
outputs = korean_model.generate(**inputs, max_new_tokens=200)

response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

VRAM 사용량: 11.60GB
VRAM 남은 양: 11.73GB
Strap top는 여성의 허리와 어깨를 돋보이게 만들어주며, 데일리웨어부터 야외 활동까지 다양한 분위기에서 활용할 수 있는 아이템입니다. 이 제품은 블랙 색상으로 제작되어 시크한 느낌을 줍니다. 또한, 넓은 어깨 스트랩은 여성스러움을 더해주며, 스트레이트 디자인으로 인해 단순하면서도 세련된 분위기를 자아냅니다. 이러한 이유로 Strap top은 다양한 옷과 매치하여 활용할 수 있는 멋진 패션 아이템입니다.

In [19]:
del qwen_model
del base_model
torch.cuda.empty_cache()

In [18]:
print(f"base_model device: {next(base_model.parameters()).device}")
print(f"korean_model device: {next(korean_model.parameters()).device}")
print(f"qwen_model device: {next(qwen_model.parameters()).device}")

base_model device: cuda:0
korean_model device: cuda:0
qwen_model device: cuda:0

In [21]:
import torch
torch.cuda.empty_cache()
print(f"VRAM 사용량: {torch.cuda.memory_allocated()/1024**3:.2f}GB")
print(f"VRAM 남은 양: {torch.cuda.memory_reserved()/1024**3:.2f}GB")
prompt = "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Strap top, 카테고리: Vest top, 색상: Black, 설명: Jersey top with narrow shoulder straps."

messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
outputs = korean_model.generate(**inputs, max_new_tokens=200)

response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

VRAM 사용량: 5.85GB
VRAM 남은 양: 10.32GB
제가 추천하는 이유는 Strap top은 일반적으로 여성용으로 많이 사용되며, Narrow shoulder straps의 디자인은 여성적인 느낌을 주고, Jersey top은 편안한 코튼 소재로 만들어져 편안하게 착용할 수 있습니다. 이러한 디자인과 소재는 많은 여성들에게 인기가 높은데, 특히 스포츠나 레저 활동에서 착용하기 좋으며, 일상에서도 착용하기 적합합니다. 또한, 이 Strap top은 단색의 Black으로 제작되어 다양한 옷과 잘 어울리며, 여성들의 스타일에 다양하게 활용할 수 있습니다.

In [ ]:
# 다양한 테스트
queries = [
    "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Summer dress, 카테고리: Dress, 색상: White, 설명: Light cotton dress with floral pattern.",
    "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Denim jacket, 카테고리: Jacket, 색상: Blue, 설명: Classic denim jacket with button closure.",
    "다음 패션 아이템을 추천하는 이유를 한국어로 작성해주세요.\n상품명: Running shoes, 카테고리: Shoes, 색상: Black, 설명: Lightweight running shoes with cushioned sole."
]

for query in queries:
    messages = [{"role": "user", "content": query}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
    outputs = korean_model.generate(**inputs, max_new_tokens=200)
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    print(f"Q: {query.split('상품명:')[1][:30]}...")
    print(f"A: {response}\n")

IndexError: list index out of range

In [51]:
query = "편안한 여름 원피스"
messages = [{"role": "user", "content": query}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
outputs = korean_model.generate(**inputs, max_new_tokens=200)
response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
#print(f"Q: {query.split('상품명:')[1][:30]}...")
print(f"A: {response}\n")

A: 알맞은 원피스를 추천해드릴 수 있습니다. 여름에 쓰는 원피스는 편안함과 실용성을 중요하게 생각해야 합니다. 그래서 저는 블루색을 주제로 한 원피스를 추천드립니다.

1. 블루셔츠 원피스:
블루셔츠와 바지를 함께 입으면 더욱 편안합니다. 블루셔츠는 투명한 색상으로, 여름철의 더위를 식혀주는 효과가 있습니다. 바지는 블루셔츠와 어울리는 패턴이나 디자인을 선택하면 더욱 매력적입니다.

2. 스웨트 원피스:
스웨트 원피스는 여름철에도 착용이 가능하며, 편안하고 실용적인 원피스입니다. 블루 컬러를

In [ ]:
messages = [{"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
outputs = korean_model.generate(**inputs, max_new_tokens=200)
response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
print(response)

1. [상품 번호 1] - [이유]
   이 상품은 검색어 '나한테 잘 맞는 옷'과 가장 잘 어울리는 이유는 'Short skirt in a woven Tencel™ lyocell blend with a high waist and detachable tie'라는 설명으로, 높은 십자가와 분리 가능한 타이가 있는 짧은 스커트입니다. 이는 다양한 키와 몸매에 맞게 잘 어울릴 수 있는 스타일이기 때문입니다.

2. [상품 번호 2] - [이유]
   이 상품은 검색어 '나한테 잘 맞는 옷'과 가장 잘 어울리는 이유는 'Long-sleeved top in soft, printed cotton jersey. Round neckline with a narrow, r'이라는 설명으로, 긴팔 티셔츠입니다. 이는 흐르는 재질의 코튼 저지로 만들어져 편안하고 자연스러운 느낌을 줍니다.

3. [상품 번호 3] - [이유]
   이 상품은 검색어 '나한테 잘 맞는 옷'과 가장 잘 어울리는 이유는 'Short skirt in a woven Tencel™ lyocell blend with a high waist and detachable tie'라는 설명으로, 높은 십자가와 분리 가능한 타이가 있는 짧은 스커트입니다. 이는 검색어와 유사한 스타일이기 때문입니다.

4. [상품 번호 4] - [이유]
   이 상품은 검색어 '나한테 잘 맞는 옷'과 가장 잘 어울리는 이유는 'Calf-length skirt in woven fabric with buttons down the front. High waist with c'라는 설명으로, 빗자루 모양의 스트랩으로 고정되는 빗자루 스커트입니다. 이는 검색어와 유사한 스타일이기 때문입니다.

5. [상품 번호 5] - [이유]
   이 상품은 검색어 '나한테 잘 맞는 옷'과 가장 잘 어울리는 이유는 'Fitted skirt in sturdy stretch jersey with an elastic

In [18]:
# 1. 모델 로드
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("./qwen")
base_model = AutoModelForCausalLM.from_pretrained(
    "./qwen",
    torch_dtype=torch.float16,
    device_map="cuda"
)
korean_model = PeftModel.from_pretrained(base_model, "./qwen_korean")
korean_model.eval()

# 2. rerank 함수
def rerank_with_llm(query, candidates, top_k=3):
    candidate_text = "\n".join([
        f"{i+1}. 상품명: {articles.iloc[idx]['prod_name']}, 카테고리: {articles.iloc[idx]['product_type_name']}, 색상: {articles.iloc[idx]['colour_group_name']}, 설명: {articles.iloc[idx]['detail_desc'][:80]}"
        for i, idx in enumerate(candidates)
    ])
    
    prompt = f"""다음 패션 아이템 중 사용자 검색어에 가장 잘 맞는 {top_k}개를 추천하는 이유를 한국어로 작성해주세요.

사용자 검색어: "{query}"

후보 상품:
{candidate_text}

반드시 {top_k}개만 선택하세요.
형식:
1. [상품 번호] - [이유]
2. [상품 번호] - [이유]
3. [상품 번호] - [이유]"""

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
    outputs = korean_model.generate(**inputs, max_new_tokens=200)
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    return response

# 3. 테스트
test_queries = [
    "편안한 여름 원피스",
    "캐주얼한 흰 티셔츠",
    "출근용 블랙 슬랙스"
]

for query in test_queries:
    print(f"\n{'='*50}")
    print(f"쿼리: {query}")
    query_embedding = st_model.encode([query])
    D, I = index.search(query_embedding.astype('float32'), k=5)
    result = rerank_with_llm(query, I[0][:5])
    print(result)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

==================================================
쿼리: 편안한 여름 원피스
1. 4 - 편안한 여름 원피스의 주요 요소 중 하나인 높은 가디건과 끈으로 고정되는 특징을 가지고 있습니다. 이는 여름에도 편안하게 입을 수 있는 원피스의 핵심 포인트입니다.
2. 2 - 편안한 여름 원피스와 연관성이 높은 반팔 바지입니다. 높은 가디건과 끈으로 고정되는 특징을 가지고 있어, 여름철에도 편안하게 입을 수 있는 옷입니다.
3. 5 - 편안한 여름 원피스와 연관성이 높은 직화복입니다. 가볍고 편안한 재질과 높은 가디건, 끈으로 고정되는 특징을 가지고 있어, 여름철

==================================================
쿼리: 캐주얼한 흰 티셔츠
1. [4] - [Sal Parka] - 이 티셔츠는 캐주얼한 스타일이며, 코튼 트윌 소재로 제작되어 있어 편안함과 함께 캐주얼한 느낌을 주기 때문입니다.
2. [1] - [Flirty Kalisi hair jewellery] - 이 경우 다른 카테고리에 속해 있으나, 헤어 액세서리로 캐주얼한 느낌을 줄 수 있는 것이므로, 사용자 검색어와 유사합니다.
3. [5] - [SPEED SUKI TANK] - 이 티셔츠는 플래시와 같은 컬러로 제작되어 있으며, 레이스 디테일과 플래시 웨이브 weave가 적용되어 있어 캐주얼한 느낌을 주는

==================================================
쿼리: 출근용 블랙 슬랙스

TypeError: 'float' object is not subscriptable

In [22]:
def rerank_with_llm(query, candidates, top_k=3):
    candidate_text = "\n".join([
        f"{i+1}. 상품명: {articles.iloc[idx]['prod_name']}, 카테고리: {articles.iloc[idx]['product_type_name']}, 색상: {articles.iloc[idx]['colour_group_name']}, 설명: {articles.iloc[idx]['detail_desc'][:80]}"
        for i, idx in enumerate(candidates)
    ])
    
    prompt = f"""당신은 패션 추천 전문가입니다. 반드시 한국어로만 답변하세요. 한자나 중국어는 절대 사용하지 마세요.

사용자 검색어: "{query}"

후보 상품:
{candidate_text}

위 후보 중 가장 적합한 {top_k}개를 선택하고 이유를 설명하세요.
형식:
1. [상품 번호] - [이유]
2. [상품 번호] - [이유]
3. [상품 번호] - [이유]"""

    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(text, return_tensors="pt").to(korean_model.device)
    outputs = korean_model.generate(**inputs, max_new_tokens=500)
    response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
    return response

query = "나한테 잘 맞는 옷"
query_embedding = st_model.encode([query])
D, I = index.search(query_embedding.astype('float32'), k=10)
result = rerank_with_llm(query, I[0][:5])
print(result)

1. [1] - 이 제품은 블랙과 베이지의 두 가지 색상을 가지고 있어서, 다양한 스타일에 어울릴 수 있습니다. 또한, 허리와 턱이 높아서 다채롭게 착용할 수 있으며, 높은 허리와 detachable ti로 세련된 느낌을 줍니다.
2. [4] - 이 제품은 블랙과 딥그레이의 두 가지 색상을 가지고 있어, 다양한 스타일에 어울릴 수 있습니다. 또한, 치수도 적절하여 착용감이 좋습니다. 그리고 쿠션감 있는 코튼 재질로 만들어져서 편안하게 착용할 수 있습니다.
3. [5] - 이 제품은 블랙과 딥퍼플의 두 가지 색상을 가지고 있어, 다양한 스타일에 어울릴 수 있습니다. 또한, 스트레치 재질로 만들어져서 편안하게 착용할 수 있으며, 부드러운 재질과 세련된 디자인으로 보는 눈에 인기가 많습니다.

In [53]:
import time

query = "편안한 여름 원피스"

t1 = time.time()
query_embedding = st_model.encode([query])
print(f"encode: {time.time()-t1:.2f}초")

t2 = time.time()
D, I = index.search(query_embedding.astype('float32'), k=10)
print(f"FAISS search: {time.time()-t2:.2f}초")

t3 = time.time()
result = rerank_with_llm(query, I[0][:5])
print(f"LLM rerank: {time.time()-t3:.2f}초")

print(result)

encode: 0.01초
FAISS search: 0.00초
LLM rerank: 46.32초
1. 4 - 편안한 여름 원피스와 가장 연관성이 높습니다. 스판덱스와 니트 재질로 제작된 하이웨스트 슬림 바디 형태의 원피스입니다.
2. 5 - 원피스 형태로 제작되어 있으며, 편안함과 함께 여성적인 느낌을 주는 디자인입니다. 또한, 핑크색으로 나와 있어 더 여성스러운 느낌을 줍니다.
3. 1 - 이 경우, 다른 아이템과는 다르게 금속 재질의 목걸이입니다. 따라서 여름 원피스와의 연관성이 떨어집니다.